#include "common.h"
#include "monsters.h"

static char *DND_MONSTERS[] = {
	"A-mi-kuk",
	"Aalpamac",
	"Aarakocra",
	"Aatxe",
	"Aaztar-ghola",
	"Abbanith Giant",
	"Abhorrent Overlord",
	"Abjurer Wizard",
	"Abjurer",
	"Aboleth",
	"Aboleth, Nihileth",
	"Abominable Beauty",
	"Abominable Yeti",
	"Abyssal Custodian",
	"Abyssal Wretch",
	"Accursed Defiler",
	"Acererak",
	"Achaeierai",
	"Acid Ant",
	"Acolyte",
	"Adherer",
	"Adolescent Dark Young",
	"Adranach",
	"Adult Amethyst Dragon",
	"Adult Bhole",
	"Adult Black Dragon",
	"Adult Blue Dracolich",
	"Adult Blue Dragon",
	"Adult Boreal Dragon",
	"Adult Brass Dragon",
	"Adult Bronze Dragon",
	"Adult Cave Dragon",
	"Adult Copper Dragon",
	"Adult Crystal Dragon",
	"Adult Dark Young",
	"Adult Deep Dragon",
	"Adult Emerald Dragon",
	"Adult Faerie Dragon",
	"Adult Flame Dragon",
	"Adult Gold Dragon",
	"Adult Green Dragon",
	"Adult Imperial Dragon",
	"Adult Kruthik",
	"Adult Light Dragon",
	"Adult Mithral Dragon",
	"Adult Moonstone Dragon",
	"Adult Oblex",
	"Adult Oblex",
	"Adult Phoenix",
	"Adult Red Dragon",
	"Adult Rime Worm",
	"Adult Sapphire Dragon",
	"Adult Sea Dragon",
	"Adult Silver Dragon",
	"Adult Topaz Dragon",
	"Adult Void Dragon",
	"Adult Wasteland Dragon",
	"Adult White Dragon",
	"Adult Wind Dragon",
	"Aeorian Absorber",
	"Aeorian Nullifier",
	"Aeorian Reverser",
	"Aerial Servant",
	"Aerisi Kalinoth (with Lair Actions)",
	"Aerisi Kalinoth",
	"Agdon Longscarf",
	"Agnibarra",
	"Ahmaergo",
	"Ahu-Nixta Cataphract",
	"Ahu-Nixta Drudge",
	"Ahu-Nixta",
	"Ahuizotl",
	"Air Elemental Myrmidon",
	"Air Elemental Myrmidon",
	"Air Elemental",
	"Akaasit",
	"Akhlut",
	"Akroan Hoplite",
	"Al-Aeshma",
	"Ala",
	"Alabaster Tree",
	"Albino Death Weasel",
	"Albino Dwarf Warrior",
	"Alchemical Apprentice",
	"Alchemical Golem",
	"Alchemical Skunk",
	"Alchemist Archer",
	"Aldani ",
	"Alehouse Drake",
	"Algoid",
	"Algorith",
	"Alhoon",
	"Alhoon",
	"Alkilith",
	"Alkilith",
	"Alkonost",
	"Alligator Turtle",
	"Alligator",
	"Allip",
	"Allip",
	"Alliumite",
	"Allosaurus",
	"Almiraj",
	"Alnaar",
	"Alp",
	"Alpha Fish",
	"Alpha Yek",
	"Alseid Grovekeeper",
	"Alseid",
	"Alseid",
	"Alsikaya, The Screeching Mother of Volcanoes",
	"Altar Flame Golem",
	"Alynn",
	"Amber Ooze",
	"Amble",
	"Ambush Drake",
	"Amethyst Dragon Wyrmling",
	"Amidor the Dandelion",
	"Ammalia Cassalanter",
	"Ammut",
	"Amnizu",
	"Amnizu",
	"Amphiptere",
	"Amphisbaena",
	"Amphoron of Yothri Juggernaut",
	"Amphoron of Yothri Warrior",
	"Amphoron of Yothri Worker",
	"Anarch",
	"Ancient Amethyst Dragon",
	"Ancient Black Dragon",
	"Ancient Blue Dragon",
	"Ancient Boreal Dragon",
	"Ancient Brass Dragon",
	"Ancient Bronze Dragon",
	"Ancient Chronomancer",
	"Ancient Copper Dragon",
	"Ancient Crystal Dragon",
	"Ancient Deep Crow",
	"Ancient Deep Dragon",
	"Ancient Dragon Turtle",
	"Ancient Emerald Dragon",
	"Ancient Flame Dragon",
	"Ancient Gold Dragon",
	"Ancient Green Dragon",
	"Ancient Imperial Dragon",
	"Ancient Light Dragon",
	"Ancient Mandriano",
	"Ancient Mithral Dragon",
	"Ancient Moonstone Dragon",
	"Ancient Red Dragon",
	"Ancient Sapphire Dragon",
	"Ancient Sea Dragon",
	"Ancient Sea Serpent",
	"Ancient Silver Dragon",
	"Ancient Titan",
	"Ancient Topaz Dragon",
	"Ancient Void Dragon",
	"Ancient Wasteland Dragon",
	"Ancient White Dragon",
	"Ancient Wind Dragon",
	"Andras",
	"Andrenjinyi",
	"Androsphinx",
	"Angatra",
	"Angel of Judgement",
	"Angelic Enforcer",
	"Angler Worm",
	"Angry Sorrowsworn",
	"Animated Armor",
	"Animated Bearskin Rug",
	"Animated Breath",
	"Animated Broom",
	"Animated Chained Library",
	"Animated Table",
	"Aniwye",
	"Ankheg",
	"Ankou Soul Herald",
	"Ankou Soul Seeker",
	"Ankylosaurus Zombie",
	"Ankylosaurus",
	"Annis Hag",
	"Annis Hag",
	"Anophiloi",
	"Ant Lion",
	"Anubian",
	"Anvilwrought Raptor",
	"Anzu",
	"Apau Perape",
	"Apaxrusl",
	"Ape",
	"Aphemia",
	"Apprentice Wizard",
	"Apprentice Wizard",
	"Arachnid Queen",
	"Arachnocrat",
	"Aranea",
	"Arasta",
	"Arbeyach",
	"Arborcyte",
	"Arboreal Grappler",
	"Arcamag",
	"Arcanaloth",
	"Arcanamite",
	"Arcanaphage",
	"Arcane Guardian",
	"Arcanoplasm",
	"Archaeopteryx",
	"Archaic",
	"Archdruid",
	"Archdruid",
	"Archduke Zariel of Avernus",
	"Archer",
	"Archer",
	"Archer",
	"Archlich",
	"Archmage",
	"Archon of Falling Stars",
	"Archon of Redemption",
	"Archon of the Triumvirate",
	"Arclight Phoenix",
	"Aribeth de Tylmarande",
	"Aridni",
	"Armanite",
	"Armanite",
	"Armed Skeleton",
	"Armor Sliver",
	"Armory Golem",
	"Arrant Quill",
	"Art Elemental Mascot",
	"Artificer of Yothri",
	"Artus Cimber",
	"Asanbosam",
	"Ascomoid",
	"Ash Drake",
	"Ash Phoenix",
	"Ashari Firetamer",
	"Ashari Skydancer",
	"Ashari Stoneguard",
	"Ashari Waverider",
	"Ashen Custodian",
	"Ashen Rider",
	"Aspect of Bahamut",
	"Aspect of Tiamat",
	"Assassin Bug",
	"Assassin Bug",
	"Assassin Vine",
	"Assassin",
	"Astral Devourer",
	"Astral Dreadnought",
	"Astral Dreadnought",
	"Astral Moth",
	"Astral Shark",
	"Astral Snapper",
	"Astri",
	"Astropal",
	"Atterroppe",
	"August Rooster",
	"Aurelia",
	"Auril (First Form)",
	"Auril (Second Form)",
	"Auril (Third Form)",
	"Aurochs",
	"Aurora Horribilis",
	"Aurumvorax",
	"Auspicia Dran",
	"Automata",
	"Autumn Eladrin",
	"Autumn Eladrin",
	"Avalanche Screamer",
	"Avarice",
	"Avatar of Atlach-Nacha",
	"Avatar of Bokrug",
	"Avatar of Boreas",
	"Avatar of Byatis",
	"Avatar of Chaugnar Faugn",
	"Avatar of Shoth",
	"Avatar of Tsathoggua",
	"Avatar of Yig",
	"Aviere",
	"Avulzor",
	"Awakened Shrub",
	"Awakened Tree",
	"Awakened Zurkhwood",
	"Axe Beak",
	"Azbara Jos",
	"Azeban",
	"Azer",
	"Azi Dahaka",
	"Azure Enchanter",
	"Azure Mind Sculptor",
	"Azza Gremlin",
	"Baalzebul",
	"Baba Lysaga",
	"Baba Lysaga's Creeping Hut",
	"Baba Yaga",
	"Baba Yaga’s Horsemen, Base",
	"Babau",
	"Babau",
	"Baboon",
	"Baby Tanglewyrm",
	"Badger",
	"Bael",
	"Bael",
	"Bagiennik",
	"Bak Mei",
	"Balhannoth",
	"Baliri",
	"Balloon Spider",
	"Balor",
	"Banderbobb",
	"Banderhobb",
	"Bandit Captain",
	"Bandit Lord",
	"Bandit",
	"Baneling",
	"Banshee",
	"Baphomet",
	"Baphomet",
	"Bar Brawl",
	"Barbatos",
	"Barbed Devil",
	"Bard",
	"Bard",
	"Barghest",
	"Barghest",
	"Barlgura",
	"Barnibus Blastwind",
	"Barometz",
	"Barong",
	"Barovian Witch",
	"Basilisk",
	"Bastet Temple Cat",
	"Bastian Thermandar",
	"Bat King",
	"Bat",
	"Bathael, the Exiled Lord",
	"Bathhouse Drake",
	"Battle Mage",
	"Battleforce Angel",
	"Bavlorna Blightstraw",
	"Bearded Devil",
	"Bearfolk Chieftan",
	"Bearfolk",
	"Bearing Golem",
	"Bearmit Crab",
	"Beast of Ill Omen",
	"Bebilith",
	"Befouled Weird",
	"Beggar Ghoul",
	"Behemoth, Terror of the Earth",
	"Behir",
	"Beholder (in lair)",
	"Beholder Dragon",
	"Beholder Zombie",
	"Beholder",
	"Behtu",
	"Belashyrra",
	"Beledros Witherbloom",
	"Beli",
	"Bellowing Tanglewyrm",
	"Belphegor, Hell's Inventor",
	"Berbalang",
	"Berchta",
	"Bereginyas",
	"Berserker",
	"Berstuc",
	"Bhaal, Ravager",
	"Bhaal, Slayer",
	"Bheur Hag",
	"Bheur Hag",
	"Bhole Hatchling",
	"Biclops",
	"Bilby",
	"Bilwis",
	"Biomancer",
	"Bjornhild Solvigsdottir",
	"Black Abishai",
	"Black Abishai",
	"Black Bear",
	"Black Crier",
	"Black Dracolisk",
	"Black Dragon Wyrmling",
	"Black Earth Guard",
	"Black Earth Priest",
	"Black Guantlet of Bane",
	"Black Knight Commander",
	"Black Knight",
	"Black Pudding",
	"Black Sun Priestess",
	"Black Sun orc",
	"Black Viper",
	"Blackguard",
	"Blackguard",
	"Blagothkus",
	"Bleakheart",
	"Blemmyes",
	"Blessed Berserker",
	"Blindhelm",
	"Blink Dog",
	"Blistercoil Weird",
	"Bloated Ghoul",
	"Blood Drinker Vampire",
	"Blood Elemental",
	"Blood Giant",
	"Blood Hag",
	"Blood Hawk",
	"Blood Hunter",
	"Blood Imp",
	"Blood Mage",
	"Blood Ooze",
	"Blood Ooze",
	"Blood Orchid Grand Savant",
	"Blood Orchid Savant",
	"Blood Orchid",
	"Blood Pudding",
	"Blood Witch",
	"Blood Zombie",
	"Blood-Toll Harpy",
	"Bloodbeast",
	"Bloodfray Giant",
	"Bloodsapper",
	"Bloodstone Sentinel",
	"Bloodsuckle",
	"Bloody Bones",
	"Bloody Bones",
	"Bloom Hydra",
	"Blue Abishai",
	"Blue Abishai",
	"Blue Dracolisk",
	"Blue Dragon Wyrmling",
	"Blue Elf",
	"Blue Slaad",
	"Boalisk",
	"Boar",
	"Bodak",
	"Bodak",
	"Bodhi Irenicus",
	"Bodytaker Plant",
	"Bog Troll",
	"Boggle",
	"Boggle",
	"Boloti",
	"Bone Cobbler",
	"Bone Collective",
	"Bone Colossus",
	"Bone Crab",
	"Bone Devil",
	"Bone Golem",
	"Bone Golem",
	"Bone Knight",
	"Bone Naga",
	"Bone Swarm",
	"Boneclaw",
	"Boneclaw",
	"Boneless",
	"Bonepowder Ghoul",
	"Boneshard Wraith",
	"Bonespitter",
	"Bonesucker",
	"Bookkeeper",
	"Boomer",
	"Boot Grabber",
	"Borborygmos",
	"Borea's Chosen",
	"Boreal Dragon Wyrmling",
	"Borivik Windheim",
	"Borsin (Ape Centaur)",
	"Bouda",
	"Brachyura Shambler",
	"Brackish Trudge",
	"Brahma Lutter",
	"Brain Hood",
	"Brain in a Jar",
	"Brains in Iron",
	"Brass Dragon Wyrmling",
	"Brass Man",
	"Bridesmaid of Zuggtmoy",
	"Bridge Troll",
	"Brigganock",
	"Brimstone Locusthound",
	"Brine Sea Serpent",
	"Bristled Moorbounder",
	"Brontosaurus",
	"Brontotherium",
	"Bronze Dragon Wyrmling",
	"Bronze Golem",
	"Bronze Sable",
	"Bronze Scout",
	"Brood Butcher",
	"Brood Monitor",
	"Brood Sliver",
	"Broodiken",
	"Broodmother of Leng",
	"Broom of Animated Attack",
	"Brother Ox",
	"Brown Bear",
	"Brume",
	"Bucca",
	"Bugbear Chief",
	"Bugbear",
	"Bukavac",
	"Bulbous Violet",
	"Bulette",
	"Bulezau",
	"Bulezau",
	"Bull",
	"Bullywug Croaker",
	"Bullywug Knight",
	"Bullywug Royal",
	"Bullywug Shaman",
	"Bullywug",
	"Buraq",
	"Burning Dervish",
	"Burning Skeleton",
	"Burnished Hart",
	"Burrowling",
	"Burrowshark",
	"Butatsch",
	"Byakhee",
	"Cackler",
	"Cackling Skeleton",
	"Cactid",
	"Cacus Giant",
	"Cadaver Collector",
	"Cadaver Lord",
	"Cadaver Sprite",
	"Cadaver",
	"Cambion",
	"Cambium",
	"Camel",
	"Campestri",
	"Canoloth",
	"Canoloth",
	"Canopic Golem",
	"Capra Demon",
	"Captain Othelstan",
	"Carbuncle",
	"Carbuncle",
	"Carnivorous Ship",
	"Carnivorous Sod",
	"Carrier Mosquito",
	"Carrion Beetle",
	"Carrion Crawler",
	"Carrion Stalker",
	"Carrionette",
	"Carytid Column",
	"Cat",
	"Category 1 Krasis",
	"Category 2 Krasis",
	"Category 3 Krasis",
	"Caterprism",
	"Catoblepas",
	"Catoblepas",
	"Catoblepas",
	"Cats of Ulthar",
	"Catscratch",
	"Cauldronborn",
	"Caustic Crawler",
	"Cavalry Scout",
	"Cave Cricket",
	"Cave Dragon Wyrmling",
	"Cave Drake",
	"Cave Eel",
	"Cave Fisher",
	"Cave Fisher",
	"Cave Fisher",
	"Cave Giant Shaman",
	"Cave Giant",
	"Cave Goat",
	"Cave Leech",
	"Cavefish Zombie",
	"Cavelight Moss",
	"Ceaseless Discharge",
	"Centaur Chieftan",
	"Centaur Mummy",
	"Centaur Skeleton",
	"Centaur",
	"Cerebral Stalker",
	"Chain Devil",
	"Chain Worm",
	"Chained Angel",
	"Chainer Geist",
	"Chamaelean",
	"Chamberlain of Zuggtmoy",
	"Chameleon Hydra",
	"Champion of Ravens",
	"Champion",
	"Champion",
	"Chamrosh",
	"Changeling",
	"Chaos Knight",
	"Chaos Quadrapod",
	"Chaos-Spawn Goblin",
	"Chardalyn Berserker",
	"Chardalyn Dragon",
	"Charnel Whisperer",
	"Chasme",
	"Chatterlome",
	"Chelicerae",
	"Chemosh, Demon Lord of Conquest",
	"Chernomoi",
	"Cherufe",
	"Child of Yggdrasil",
	"Child of the Briar",
	"Chill Haunt",
	"Chimera",
	"Chimeric Phantom",
	"Chitine",
	"Chittr'k'k, Demon Lord of Rats",
	"Choker",
	"Choker",
	"Choldrith",
	"Choldrith",
	"Chort",
	"Chromatic Greatwyrm",
	"Chronalmental",
	"Chronomatic Enhancer",
	"Chuhaister",
	"Chupacabra",
	"Chupacabra",
	"Chupacabra",
	"Church Grim",
	"Churr",
	"Chuul Spore Servant",
	"Chuul",
	"Chwinga",
	"Cikavak",
	"Cimota Guardian",
	"Cimota",
	"Cinderslag Elemental",
	"Cipactli",
	"City Watch Captain",
	"Clacking Skeleton",
	"Clamor",
	"Clapperclaw the Scarecrow",
	"Clasp Cutthroat",
	"Clasp Enforcer",
	"Claw of Sha'argon",
	"Clawfoot",
	"Clay Golem",
	"Cleric of the Brew",
	"Cloaker",
	"Clockwork Abomination",
	"Clockwork Archon",
	"Clockwork Assassin",
	"Clockwork Beetle Swarm",
	"Clockwork Beetle",
	"Clockwork Bronze Scout",
	"Clockwork Dragon",
	"Clockwork Dragon",
	"Clockwork Hound",
	"Clockwork Huntsman",
	"Clockwork Iron Cobra",
	"Clockwork Kraken",
	"Clockwork Leech",
	"Clockwork Mantis",
	"Clockwork Myrmidon",
	"Clockwork Oaken Bolter",
	"Clockwork Pest",
	"Clockwork Servant",
	"Clockwork Soldier",
	"Clockwork Stone Defender",
	"Clockwork Tiger",
	"Clockwork Watchman",
	"Clockwork Weaving Spider",
	"Cloud Giant Ghost",
	"Cloud Giant Smiling One",
	"Cloud Giant Smiling One",
	"Cloud Giant",
	"Clurichaun",
	"Cobalt Golem",
	"Cobbleswarm",
	"Cobra Flower",
	"Cockatrice",
	"Coffer Corpse",
	"Cogwork Archivist",
	"Cold Snap Spirit",
	"Coldlight Walker",
	"Collais",
	"Colossus of Akros",
	"Colour out of Space",
	"Commander of Horn and Gold",
	"Commoner",
	"Compsognathus",
	"Conclave Dryad",
	"Conjoined Queen",
	"Conjurer Wizard",
	"Conjurer",
	"Conquest",
	"Constrictor Snake",
	"Constructed Commoner",
	"Control Drone",
	"Cooshee",
	"Copper Dragon Wyrmling",
	"Coral Drake",
	"Core Spawn Crawler",
	"Core Spawn Emissary",
	"Core Spawn Seer",
	"Core Spawn Worm",
	"Cornelius Watson",
	"Corpse Flower",
	"Corpse Flower",
	"Corpse Mound",
	"Corpse Rook",
	"Corpse Thief",
	"Corpse Worm",
	"Corpsespinner",
	"Corpsespun",
	"Corrupted Avatar of Lurue",
	"Corrupted Ogre Chieftain",
	"Corrupted Pixie",
	"Corrupting Ooze",
	"Corruptor",
	"Couatl",
	"Counterflux Blastseeker",
	"Coven Horror",
	"Cow",
	"Crab Folk",
	"Crab",
	"Crabman",
	"Crag Cat",
	"Cranium Rat",
	"Cranium Rat",
	"Crater Drake",
	"Crawling Claw",
	"Creepy Doll",
	"Crimson Basilisk",
	"Crimson Drake",
	"Crimson Mist",
	"Crimson Mist",
	"Crimson Shambler",
	"Crinaea",
	"Criosphinx",
	"Crockek'toeck",
	"Crocodile",
	"Crocotta",
	"Crowlock",
	"Cruorbat",
	"Cruorgheist",
	"Cruorhulk",
	"Crushing Wave Priest",
	"Crushing Wave Reaver",
	"Cryoceros",
	"Cryonax",
	"Crypt Lurker",
	"Crypt Spider",
	"Crypt Thing",
	"Crystal Dragon Wyrmling",
	"Crystal Elemental",
	"Crystalline Devil",
	"Crystalline Dragon",
	"Crystalline Monolith",
	"Crystalline Sliver",
	"Cthurkey",
	"Cueyatl Moon Priest",
	"Cueyatl Sea Priest",
	"Cueyatl Warrior",
	"Cueyatl",
	"Culicoid",
	"Cult Fanatic",
	"Cult Killer",
	"Cult Mastermind",
	"Cultist",
	"Curse of Strahdmotronic Blastseeker",
	"Cursed oak",
	"Cyclops Stormcaller",
	"Cyclops",
	"Daemogoth Titant",
	"Daemogoth",
	"Dagon",
	"Dagryn",
	"Dancing Foliage",
	"Dao",
	"Darakhul Captain",
	"Darakhul High Priestess",
	"Darakhul Shadowmancer",
	"Darakhul Spy",
	"Darakhul",
	"Darien",
	"Dark Creeper",
	"Dark Eye",
	"Dark Father",
	"Dark Servant",
	"Dark Stalker",
	"Dark Tide Knight",
	"Dark Triton",
	"Dark Voice",
	"Darkling Elder",
	"Darkling Elder",
	"Darkling",
	"Darkling",
	"Darkmantle",
	"Darkwraith",
	"Darnoc",
	"Dau",
	"Daughter of Sub-Niggurath",
	"Davil Starson",
	"De Ogen",
	"Death Barque",
	"Death Butterfly Swarm",
	"Death Butterfly Swarm, Greater",
	"Death Dog",
	"Death Kiss",
	"Death Kiss",
	"Death Knight",
	"Death Shroud Golem",
	"Death Slaad",
	"Death Speaker",
	"Death Tyrant (in lair)",
	"Death Tyrant",
	"Death Vulture",
	"Death Widow",
	"Death Worm",
	"Death",
	"Death's Head of Bhaal",
	"Death's Head",
	"Deathcap Myconid",
	"Deathcrest Ape",
	"Deathless Wizard",
	"Deathlock Mastermind",
	"Deathlock Mastermind",
	"Deathlock Wight",
	"Deathlock Wight",
	"Deathlock",
	"Deathlock",
	"Deathpact Angel",
	"Deathsworn",
	"Deathweaver",
	"Deathwisp",
	"Decapus",
	"Decapus",
	"Deep Crow",
	"Deep Dragon Wyrmling",
	"Deep Drake",
	"Deep Hunter Sea Serpent",
	"Deep One Archimandrite",
	"Deep One Bishop",
	"Deep One Hybrid Cultist",
	"Deep One Hybrid Priest",
	"Deep One Scion Priest of Cthulhu",
	"Deep One",
	"Deep One",
	"Deep One",
	"Deep Rothe",
	"Deep Scion",
	"Deep Scion",
	"Deep Spider",
	"Deep Troll",
	"Deep Troll",
	"Deer",
	"Degenerate Titan",
	"Degmadu",
	"Deinonychus",
	"Demilich (in lair)",
	"Demilich",
	"Demodand, Farastu",
	"Demodand, Kelubar",
	"Demodand, Shator",
	"Demogorgon",
	"Demogorgon",
	"Demogorgon",
	"Demon Lord of Apes, Mechuiti",
	"Demon Lord of Bats and Fire Camazotz",
	"Demon Lord of Cockroaches Akyishigal",
	"Demon Lord of Night Alquam",
	"Demon Lord of the Devouring Worm Qorgeth",
	"Demonfeed Spider",
	"Demonfeed Spiderling",
	"Demonic Knight",
	"Demos Magen",
	"Denizen of Leng",
	"Derendian Moth Abomination",
	"Derro Explorer",
	"Derro Fetal Savant",
	"Derro Guard",
	"Derro Savant",
	"Derro Savant",
	"Derro Servant",
	"Derro Shadow Antipaladin",
	"Derro Shadowseeker",
	"Derro",
	"Derro",
	"Desert Giant",
	"Desert Troll",
	"Despair",
	"Deva",
	"Devil Bough",
	"Devil Shark",
	"Devilbound Gnomish Prince",
	"Devkarin Lich",
	"Devourer",
	"Dhampir Commander",
	"Dhampir",
	"Dhergoloth",
	"Dhergoloth",
	"Dhole Adult",
	"Dhole Hatchling",
	"Dimenshional Shambler",
	"Dimensional Shambler",
	"Dimetrodon",
	"Diminution Drake",
	"Dipsa",
	"Dire Anglerfish",
	"Dire Corby",
	"Dire Corby",
	"Dire Troll",
	"Dire Wolf",
	"Dirt-Under-Nails",
	"Displacer Beast Kitten",
	"Displacer Beast",
	"Dissimortuum",
	"Diviner Wizard",
	"Diviner",
	"Djinni",
	"Dogmole Juggernaut",
	"Dogmole",
	"Dolgaunt",
	"Dolgrim",
	"Dolphin Delighter",
	"Dolphin",
	"Domovoi",
	"Donaar Blit'zen",
	"Doom Golem",
	"Doombat",
	"Doomspeaker",
	"Doomwake Giant",
	"Doppelganger",
	"Doppelrat",
	"Dorreq",
	"Doty X",
	"Dracoform Eremite Symbiont",
	"Dracoform-Bound Eremite",
	"Dracohydra",
	"Draconian Dreadnought",
	"Draconian Footsoldier",
	"Draconian Infiltrator",
	"Draconian Mage",
	"Draconian Mastermind",
	"Draconic Amalgam",
	"Draconic Shard",
	"Dracotaur",
	"Draegloth",
	"Draegloth",
	"Draegloth",
	"Draft Horse",
	"Dragon Blessed",
	"Dragon Chosen",
	"Dragon Eel",
	"Dragon Speaker",
	"Dragon Tortoise",
	"Dragon Turtle Wyrmling",
	"Dragon Turtle",
	"Dragonbait",
	"Dragonblood Ooze",
	"Dragonbone Golem",
	"Dragonborn of Bahamut",
	"Dragonborn of Sardior",
	"Dragonborn of Tiamat",
	"Dragonclaw",
	"Dragonfang",
	"Dragonflesh Abomination",
	"Dragonflesh Golem",
	"Dragonflesh Grafter",
	"Dragonleaf Tree",
	"Dragonnel",
	"Dragonslayer Ornstein",
	"Dragonsoul",
	"Dragonwing",
	"Drakon",
	"Dralmorrer Borngray",
	"Drannin Splithelm",
	"Dread Doppelganger",
	"Dread Walker Excavator",
	"Dread Warrior",
	"Dream Eater",
	"Dream Eater",
	"Dream Squire",
	"Dream Wraith",
	"Dreamlands Cat",
	"Dreamlands Cat, Saturnian",
	"Dreamlands Cat, Uranian",
	"Dretch",
	"Drider",
	"Droki",
	"Droth",
	"Drow Arachnomancer",
	"Drow Arachnomancer",
	"Drow Elite Warrior",
	"Drow Favored Consort",
	"Drow Favored Consort",
	"Drow Gunslinger",
	"Drow House Captain",
	"Drow House Captain",
	"Drow Inquisitor",
	"Drow Inquisitor",
	"Drow Mage",
	"Drow Matron Mother",
	"Drow Matron Mother",
	"Drow Mech",
	"Drow Priestess of Lolth",
	"Drow Shadowblade",
	"Drow Shadowblade",
	"Drow Spore Servant",
	"Drow",
	"Drowned Ascetic",
	"Drowned Assassin",
	"Drowned Blade",
	"Drowned Maiden",
	"Drowned Master",
	"Druid of the Old Ways",
	"Druid",
	"Dryad",
	"Du'ulora Quori",
	"Dualist Shadow Fey Elves",
	"Duergar Darkhaft",
	"Duergar Despot",
	"Duergar Despot",
	"Duergar Hammerer",
	"Duergar Hammerer",
	"Duergar Kavalrachni",
	"Duergar Keeper Of The Flame",
	"Duergar Mind Master",
	"Duergar Screamer",
	"Duergar Screamer",
	"Duergar Soulblade",
	"Duergar Soulblade",
	"Duergar Spore Servant",
	"Duergar Spy",
	"Duergar Stone Guard",
	"Duergar Stone Guard",
	"Duergar Warlord",
	"Duergar Warlord",
	"Duergar Xarrorn",
	"Duergar Xarrorn",
	"Duergar",
	"Dullahan",
	"Dullahan",
	"Dune Mimic",
	"Duodrone",
	"Durnan",
	"Dusk Hag",
	"Duskdale Wurm",
	"Duskdale Wurm",
	"Duskthorn Dryad",
	"Dust Digger",
	"Dust Goblin Cheiftan",
	"Dust Goblin",
	"Dust Mephit",
	"Dvarapala",
	"Dwarven Ringmage",
	"Dwarven Worker",
	"Dybbuk",
	"Dybbuk",
	"Dyrrn",
	"Dzaan's Simulacrum",
	"Eagle",
	"Eala",
	"Earth Elemental Myrmidon",
	"Earth Elemental Myrmidon",
	"Earth Elemental",
	"Eater of Dust",
	"Eater of Hope",
	"Eblis",
	"Eblis",
	"Echo",
	"Ecstatic Bloom",
	"Ectoplasm",
	"Edimmu",
	"Edjet Initiate",
	"Edjet",
	"Edwin Odesseiron",
	"Eel Hound",
	"Efreeti",
	"Egg Hunter Adult",
	"Egg Hunter Hatchling",
	"Egret Harpy",
	"Eidolon",
	"Einherjar",
	"Elder Brain Dragon",
	"Elder Brain",
	"Elder Brain",
	"Elder Ghost Boar",
	"Elder Oblex",
	"Elder Oblex",
	"Elder Shadow Drake",
	"Elder Tempest",
	"Elder Thing",
	"Eldrazi Scion",
	"Eldritch Ooze",
	"Eleinomae",
	"Elemental Locus",
	"Elementalist",
	"Elephant",
	"Elfmarked Human",
	"Elise",
	"Elite Kobold",
	"Elizar Dryflagon",
	"Elk",
	"Elkhorn",
	"Elophar",
	"Elusa Hound",
	"Elvish Veteran Archer",
	"Ember Roc",
	"Emerald Dragon Wyrmling",
	"Emerald Eye",
	"Emerald Order Cult Leader",
	"Emperor Ghoul",
	"Emperor's Hyena",
	"Empty Cloak",
	"Empusa",
	"Empyrean",
	"Emrakul, The Aeons Torn",
	"Encephalon Gorger",
	"Enchanter Wizard",
	"Enchanter",
	"Enchanter",
	"Enchantress Shadow Fey Elves",
	"Endelyn Moongrave",
	"Enhanced Medusa",
	"Envoker",
	"Eo Ashmajiir",
	"Eonic Drifter",
	"Eonic Savant",
	"Eremite Symbiont",
	"Eremite",
	"Erina Defender",
	"Erina Scrounger",
	"Erinyes",
	"Etali, Primal Storm",
	"Eternal Flame Guardian",
	"Eternal Flame Priest",
	"Ettercap",
	"Ettin",
	"Evil Doll",
	"Evil Mage",
	"Evoker Wizard",
	"Evoker",
	"Execrable Shrub",
	"Executioner Smough",
	"Expeditious Messenger",
	"Exploding Toad",
	"Eye Golem",
	"Eye of Fear and Flame",
	"Eye of the Gods",
	"Eye of the Watcher",
	"Eyedrake",
	"Ezmerelda d'Avenir",
	"Fabricator",
	"Faceless Wanderer",
	"Faerl",
	"Faldorn the Heirophant",
	"Fallen Angel",
	"Falsifier Fog",
	"Famine",
	"Fane Spirit",
	"Fang of the Great Wolf",
	"Fanged Sea Serpent",
	"Far Darrig",
	"Far Dorocha",
	"Far Wanderer",
	"Fastieth",
	"Fate Eater",
	"Father Dagon",
	"Father Dagon",
	"Fathomer",
	"Favored One of Nyarlathotep",
	"Fear Guard",
	"Fear Liath",
	"Fear Smith (Fiarsídhe)",
	"Fear",
	"Feathergale Knight",
	"Felid Dragon",
	"Felidar",
	"Felidar",
	"Fellforged",
	"Female Steeder",
	"Fen Witch",
	"Fennec Fox",
	"Feral Undead Cat",
	"Fern Lizard",
	"Fetch",
	"Fext",
	"Fey Drake",
	"Fey Lord of the Hunt",
	"Fey Lord, Bear King",
	"Fey Lord, Moonlit King",
	"Fey Lord, River King",
	"Fey Queen of Night and Magic",
	"Fey Queen of Witches",
	"Fey Revenant",
	"Fey Snow Queen",
	"Feyote",
	"Feyward Tree",
	"Fhenimore (Kraken Priest Variant)",
	"Fidele Angel",
	"Fiendish Flesh Golem",
	"Fierstjerren",
	"Fire Dancer Swarm",
	"Fire Drake",
	"Fire Elemental Myrmidon",
	"Fire Elemental Myrmidon",
	"Fire Elemental",
	"Fire Giant Dreadnought",
	"Fire Giant Dreadnought",
	"Fire Giant",
	"Fire Imp",
	"Fire Snake",
	"Fire Vampire",
	"Fire-Infused Water Elemental",
	"Firebird",
	"Firefist",
	"Firegeist",
	"Firemane Angel",
	"Firenewt Giant Strider",
	"Firenewt Warlock of Imix",
	"Firenewt Warlock of Imix",
	"Firenewt Warrior",
	"Firenewt Warrior",
	"First-Year Student",
	"First-Year Student",
	"Fist of Bane",
	"Five Spire Initiate",
	"Flab Giant",
	"Flabbergast",
	"Flagstone Golem",
	"Flail Snail",
	"Flail Snail",
	"Flail Snail",
	"Flame Dragon Wyrmling",
	"Flame Eater Swarm",
	"Flame-Scourged Scion",
	"Flameskull",
	"Flamewrath",
	"Flaming Skeleton",
	"Flayed Wraith",
	"Fleecemane Lion",
	"Flesh Golem",
	"Flesh Reaver",
	"Fleshdreg",
	"Fleshfiend",
	"Fleshling Bloodletter",
	"Fleshling",
	"Fleshpod Hornet",
	"Fleshspurned",
	"Fleshwurm",
	"Flimp Shagglecran",
	"Flind",
	"Flind",
	"Flithidir",
	"Flitterstep Eidolon",
	"Flowershroud",
	"Flumph",
	"Flutterflesh",
	"Flux Blastseeker",
	"Fluxcharger",
	"Flying Ape",
	"Flying Horror",
	"Flying Monkey",
	"Flying Polyp Body",
	"Flying Polyp",
	"Flying Rocking Horse",
	"Flying Snake",
	"Flying Sword",
	"Fog Giant",
	"Folk of Leng",
	"Fomorian",
	"Foo Dog",
	"Forest Drake",
	"Forest Emperor",
	"Forest Falcon",
	"Forest Hunter Shadow Fey Elves",
	"Forest Marauder",
	"Forester's Bane",
	"Forge Guardian",
	"Forlarren",
	"Formless Spawn",
	"Four-Armed Gargoyle",
	"Fox",
	"Foxfire Ooze",
	"Foxin",
	"Foxwere",
	"Fractal Golem",
	"Fractal Mascot",
	"Fragrant one",
	"Fragrite",
	"Fraughashar",
	"Fraz-Urb'luu",
	"Fraz-Urb'luu",
	"Frilled Deathspitter",
	"Frog",
	"Froghemoth",
	"Froghemoth",
	"Froghemoth",
	"Froghoul",
	"Frontline Medic",
	"Frost Druid",
	"Frost Giant Everlasting One",
	"Frost Giant Jarl",
	"Frost Giant Skeleton",
	"Frost Giant Zombie",
	"Frost Giant",
	"Frost Mole",
	"Frost Salamander",
	"Frost Worm",
	"Frostveil",
	"Frulam Mondath",
	"Fulad-Zereh",
	"Fulminar",
	"Fungal Servant",
	"Fungoid",
	"Fungus Bat",
	"Fungus Gargoyle",
	"Furnace Golem",
	"Fusion Elemental",
	"Future Yithian",
	"Fyr",
	"Gaki",
	"Galazeth Prismari",
	"Galeb Duhr",
	"Galidroo",
	"Gallows Speaker",
	"Gallows Tree Zombie",
	"Gallows Tree",
	"Galvan Magen",
	"Galvanic Blastseeker",
	"Galvanice Weird",
	"Gar Shatterkeel (with Lair Actions)",
	"Gar Shatterkeel",
	"Gargoctopus",
	"Gargoyle",
	"Garlicle",
	"Garret Levistusson",
	"Garroter Crab",
	"Gas Spore",
	"Gaunt One",
	"Gauth",
	"Gazellean",
	"Gazer",
	"Gbahali",
	"Gear Mage",
	"Gearforged Templar",
	"Gearkeeper Construct",
	"Geist",
	"Gelatinous Cube",
	"Gelectrode",
	"Gem Greatwyrm",
	"Gem Stalker",
	"Geonid",
	"Gerridae",
	"Geryon",
	"Geryon",
	"Ghald",
	"Ghalta, Primal Hunger",
	"Ghast of Leng",
	"Ghast",
	"Ghillie Dubh",
	"Ghost Ammonite",
	"Ghost Boar",
	"Ghost Dragon",
	"Ghost Dragon",
	"Ghost Dwarf",
	"Ghost Knight",
	"Ghost of Ib",
	"Ghost",
	"Ghostblade Eidolon",
	"Ghostwalk Spider",
	"Ghoul Bat",
	"Ghoul",
	"Ghoulsteed",
	"Ghul",
	"Giant Albino Bat",
	"Giant Ant Exoskeleton",
	"Giant Ant Queen",
	"Giant Ant",
	"Giant Ape",
	"Giant Armadillo",
	"Giant Badger",
	"Giant Bat",
	"Giant Beetle Exoskeleton",
	"Giant Boar",
	"Giant Bombardier Beetle",
	"Giant Centipede",
	"Giant Clam",
	"Giant Constrictor Snake",
	"Giant Coral Snake",
	"Giant Crab Exoskeleton",
	"Giant Crab",
	"Giant Crayfish",
	"Giant Crocodile",
	"Giant Dragonfly",
	"Giant Eagle",
	"Giant Eel",
	"Giant Electric Catfish",
	"Giant Elk",
	"Giant Fire Beetle",
	"Giant Four-Armed Gargoyle",
	"Giant Frilled Lizard",
	"Giant Frog",
	"Giant Goat",
	"Giant Honey Bee",
	"Giant Horsefly",
	"Giant Husk",
	"Giant Hyena",
	"Giant Ice Toad",
	"Giant Leech",
	"Giant Lightning Eel",
	"Giant Lizard",
	"Giant Mongoose",
	"Giant Moray Eel",
	"Giant Moth",
	"Giant Octopus",
	"Giant Owl",
	"Giant Poisonous Snake",
	"Giant Rat",
	"Giant Rhinoceros Beetle",
	"Giant Rimewing Moth",
	"Giant Scorpion",
	"Giant Sea Eel",
	"Giant Sea Horse",
	"Giant Sea Horse",
	"Giant Shark Bowl",
	"Giant Shark",
	"Giant Shockwing Moth",
	"Giant Skeleton",
	"Giant Slicer Beetle",
	"Giant Sloth",
	"Giant Slug of P'nahk",
	"Giant Snail",
	"Giant Snow Beetle",
	"Giant Sootwing Moth",
	"Giant Spider",
	"Giant Strider",
	"Giant Strider",
	"Giant Subterranean Lizard",
	"Giant Toad",
	"Giant Vampire Bat",
	"Giant Vulture",
	"Giant Walrus",
	"Giant Wasp",
	"Giant Water Beetle",
	"Giant Water Scorpion",
	"Giant Weasel",
	"Giant Wolf Spider",
	"Giat Snapping Turtle",
	"Gibbering Mouther",
	"Gibberling",
	"Giff",
	"Gilded Devil",
	"Gill-man",
	"Gillmonkey",
	"Gingwatzim",
	"Ginormous Squirrel",
	"Girallon Zombie",
	"Girallon",
	"Gishath, Sun's Avatar",
	"Githyanki Anarch",
	"Githyanki Enlightened",
	"Githyanki Gish",
	"Githyanki Gish",
	"Githyanki Kith'rak",
	"Githyanki Kith'rak",
	"Githyanki Knight",
	"Githyanki Supreme Commander",
	"Githyanki Supreme Commander",
	"Githyanki Warrior",
	"Githzerai Anarch",
	"Githzerai Enlightened",
	"Githzerai Monk",
	"Githzerai Zerth",
	"Glabrezu",
	"Glacial Corruptor",
	"Glacial Ooze",
	"Glacier Behemoth",
	"Gladeborn Hunter",
	"Gladeborn Trapper",
	"Gladiator",
	"Glass Gator",
	"Glass Golem",
	"Glasswork Golem",
	"Gloamwing",
	"Gloom Crawler",
	"Gloom Flower",
	"Gloom Weaver",
	"Gloomstalker",
	"Glory",
	"Gnarljak",
	"Gnarlwood",
	"Gnoll Deathknight",
	"Gnoll Deathmage",
	"Gnoll Fang of Yeenoghu",
	"Gnoll Flesh Gnawer",
	"Gnoll Flesh Gnawer",
	"Gnoll Havoc Runner",
	"Gnoll Hunter",
	"Gnoll Hunter",
	"Gnoll Pack Lord",
	"Gnoll Slaver",
	"Gnoll Vampire",
	"Gnoll Witherling",
	"Gnoll Witherling",
	"Gnoll",
	"Gnome Ceremorph",
	"Gnome Squidling",
	"Gnomish Knife Cultist",
	"Gnoph-Keh",
	"Gnorri Hunter",
	"Goat",
	"Goat-Knight Steed",
	"Goat-Man",
	"Goblin Alchemist",
	"Goblin Boss",
	"Goblin Ritualist",
	"Goblin",
	"Gohl (Hydra Cloud)",
	"Gold Dragon Wyrmling",
	"Gold-Forged Sentinel",
	"Golden Cat",
	"Golgari Shaman",
	"Goliath Longlegs",
	"Goliath Warrior",
	"Goliath Werebear",
	"Gorao-Ka",
	"Gorbel",
	"Goreling",
	"Gorgimera",
	"Gorgon",
	"Gorilla Bear",
	"Goristro",
	"Graknork",
	"Grandfather Oak",
	"Grave Behemoth",
	"Grave Sage",
	"Grave Titan",
	"Gravecrawler",
	"Graveslayer",
	"Graveyard Dragon",
	"Gray Nisp",
	"Gray Ooze",
	"Gray Orc",
	"Gray Render",
	"Gray Render",
	"Gray Slaad",
	"Gray Thirster",
	"Graz'zt",
	"Graz'zt",
	"Great Gray Owl",
	"Great Grey Wolf Sif",
	"Greater Basilisk",
	"Greater Boneneedle",
	"Greater Fire Crab",
	"Greater Ghast of Leng",
	"Greater Lunarchidna",
	"Greater Rakshasa",
	"Greater Scrag",
	"Greater Star Spawn Emissary",
	"Greater Zombie",
	"Greed Swarm",
	"Green Abishai",
	"Green Abishai",
	"Green Abyss Orc",
	"Green Brain",
	"Green Dracolisk",
	"Green Dragon Wyrmling",
	"Green Guardian Gargoyle",
	"Green Hag",
	"Green Knight of the Woods",
	"Green Slaad",
	"Grell",
	"Gremishka",
	"Gremlin",
	"Grick Alpha",
	"Grick",
	"Griffon Cavalry Rider",
	"Griffon",
	"Grim Jester",
	"Grimlock",
	"Grimm",
	"Grimmlet Swarm",
	"Grimmlet",
	"Grindylow",
	"Grippli Warrior",
	"Grippli",
	"Grisha",
	"Groff",
	"Grog Strongjaw",
	"Grove Bear",
	"Grove Guardian",
	"Grue (type 1)",
	"Grue (type 2)",
	"Grung Elite Warrior",
	"Grung Elite Warrior",
	"Grung Wildling",
	"Grung Wildling",
	"Grung",
	"Grung",
	"Gruul Goblin",
	"Guard Drake",
	"Guard Drake",
	"Guard",
	"Guardian Giant",
	"Guardian Naga",
	"Guardian Portrait",
	"Guardian Shadow Fey Elves",
	"Gug",
	"Gug",
	"Gug",
	"Gugalanna",
	"Guiguai",
	"Gulon",
	"Gulper Behemoth",
	"Gulper Eel",
	"Gumienniki",
	"Gunvald Halraggson",
	"Gynosphinx",
	"Gypsosphinx",
	"Hadrosaurus",
	"Hag of the Fetid Gaze",
	"Hair Golem",
	"Halaster Blackcloak",
	"Haleshi",
	"Half-Black Dragon Warlord",
	"Half-Orc Warpriest",
	"Half-Red Dragon Veteran",
	"Half-ogre",
	"Half-orc Barbarian",
	"Hallowed Reed",
	"Hamadryad",
	"Hanged Man",
	"Hangman Tree",
	"Hantu Penanggal",
	"Hanu-naga",
	"Harbinger of Wrath",
	"Hare",
	"Harefolk",
	"Harengon Brigand",
	"Harengon Sniper",
	"Harpy Matriarch",
	"Harpy",
	"Hashalaq Quori",
	"Hastur",
	"Haugbui",
	"Haunted Giant",
	"Hawanar Genie",
	"Hawk",
	"Hawkfox",
	"Hawktoad",
	"Headless Horseman",
	"Heavy Cavalry",
	"Hebi-Doku",
	"Heggarna",
	"Helashruu",
	"Helix Moth Adult",
	"Helix Moth Larva",
	"Hell Hound",
	"Hellenrae",
	"Hellfire Engine",
	"Hellfire Engine",
	"Hellwasp",
	"Helmed Horror",
	"Herald of Blood",
	"Herald of Darkness",
	"Herald of Fire",
	"Herald of Rot",
	"Herald of Slaughter",
	"Herald of Undeath",
	"Herald of the Great Wyrm",
	"Herald of the Void",
	"Hezrou",
	"Hieroglyphicroc",
	"Hierophant Lich",
	"High Cimota",
	"High Priest of Shub-Niggurath",
	"Hill Giant",
	"Hippocamp",
	"Hippocampus",
	"Hippogriff",
	"Hlam",
	"Hoar Fox",
	"Hoard Drake",
	"Hoard Golem",
	"Hoard Mimic",
	"Hoard Scarab",
	"Hoarfrost Drake",
	"Hobgoblin Captain",
	"Hobgoblin Devastator",
	"Hobgoblin Devastator",
	"Hobgoblin Iron Shadow",
	"Hobgoblin Iron Shadow",
	"Hobgoblin Warlord",
	"Hobgoblin",
	"Hodag",
	"Holler Spider",
	"Hollow Dragon",
	"Hollyphant",
	"Homarid",
	"Homunculus",
	"Hongaek",
	"Hooden Horse",
	"Hook Horror Spore Servant",
	"Hook Horror",
	"Horakh",
	"Horizonback Tortoise",
	"Horncaller",
	"Horned Devil",
	"Horned Serpent",
	"Hound of Tindalos",
	"Hound of Tindalos",
	"Hound of the Night",
	"Howler Baboon",
	"Howler",
	"Howler",
	"Howling Hatred Initiate",
	"Howling Hatred Priest",
	"Hrabbaz",
	"Hraesvelgr the Corpse Swallower",
	"Hriggala, Jaws of the Unsated God",
	"Huecambra",
	"Huggermugger",
	"Huli Jing",
	"Hulking Crab",
	"Hulking Whelp",
	"Hundred-Handed One",
	"Hundun",
	"Hungry Sorrowsworn",
	"Hunter Shark",
	"Hunting Horror",
	"Hunting Horror",
	"Hurricane",
	"Husk Zombie",
	"Husk",
	"Hutijin",
	"Hutijin",
	"Hverhuldra",
	"Hyaenodon",
	"Hybrid Brute",
	"Hybrid Flier",
	"Hybrid Poisoner",
	"Hybrid Shocker",
	"Hybrid Spy",
	"Hydra",
	"Hydralisk",
	"Hydroloth",
	"Hydroloth",
	"Hyena",
	"Hypnos Magen",
	"Hythonia",
	"Ia’Affrat",
	"Ice Bogie",
	"Ice Devil",
	"Ice Drake",
	"Ice Elemental",
	"Ice Golem",
	"Ice Maiden",
	"Ice Mephit",
	"Ice Toad",
	"Ice Troll",
	"Ice Troll",
	"Icewind Kobold Zombie",
	"Icewind Kobold",
	"Ichneumon",
	"Ichor Ooze",
	"Idolic Deity",
	"Iggwilv the Witch Queen",
	"Igniguana",
	"Ijiraq",
	"Ikuchi",
	"Illhveli, Kembingur",
	"Illhveli, Nauthveli",
	"Illthid Claw",
	"Illusionist Wizard",
	"Illusionist",
	"Imix",
	"Immature Slime Mold",
	"Immortal Lotus Monk",
	"Imoen",
	"Imp Dragon",
	"Imp",
	"Imperial Dragon Wyrmling",
	"Imperial Ghoul",
	"Imy-Ut Ushabti",
	"Incarnate Gloom",
	"Incinis",
	"Incubus",
	"Indentured Spirit",
	"Indominus Rex",
	"Infantryman",
	"Infernal Centaur",
	"Infernal Knight",
	"Infernal Swarm",
	"Infestation Swarm",
	"Infestor",
	"Initiate of the Elder Elementals",
	"Ink Devil",
	"Ink Guardian",
	"Inkling Mascot",
	"Inkling",
	"Inquisitor of the Mind Fire",
	"Inquisitor of the Sword",
	"Inquisitor of the Tome",
	"Inspired",
	"Intellect Devourer",
	"Invisible Stalker",
	"Irid",
	"Iron Cobra",
	"Iron Consul",
	"Iron Defender",
	"Iron Ghoul",
	"Iron Golem",
	"Iron Golem",
	"Iron Sphere",
	"Iron Teeth of Baba Yaga",
	"Ironscale Hydra",
	"Isolde",
	"Isonade",
	"Isperia",
	"Issar Kronenstrom",
	"Istrid Horn",
	"Ixitxachitl Cleric",
	"Ixitxachitl",
	"Iymrith The Dragon",
	"Izek Strazni",
	"Jaanavar Jal",
	"Jabberwock",
	"Jack of Strings",
	"Jack-in-Irons Giant",
	"Jackal of Darkness",
	"Jackal",
	"Jackalwere",
	"Jaculi",
	"Jaculi",
	"Jaculus",
	"Jade Tigress",
	"Jaheira",
	"Jalester Silvermane",
	"Jamna Gleamsilver",
	"Jarlaxle Baenre",
	"Jarod Vod Savo",
	"Jarund Elkhardt",
	"Jermlaine",
	"Jiangshi",
	"Jiangshi",
	"Jim Darkmagic",
	"Jinmenju",
	"Jon Irenicus",
	"Jotun Giant",
	"Jourrael, the Caedogeist",
	"Juiblex",
	"Juiblex",
	"Junk Shaman",
	"Jupiter Bloodsucker",
	"Juvenile Kraken",
	"J’ba Fofi",
	"K'Tulah",
	"K'thriss Drow'b",
	"Kachlian",
	"Kagain",
	"Kalag",
	"Kalaraq Quori",
	"Kalashtar",
	"Kalka-Kylla",
	"Kalke",
	"Kallikantzaros",
	"Kamadan",
	"Kamadan",
	"Kamaitachi",
	"Kampfult",
	"Kaorti",
	"Kapi",
	"Kappa",
	"Kapre",
	"Karakura",
	"Karrnathi Undead Soldier",
	"Kaveph",
	"Kavu Predator",
	"Kech",
	"Keelbreaker Crab",
	"Keg Golem",
	"Keg Robot",
	"Kelek",
	"Kelp Drake",
	"Kelp Eel",
	"Kelpie",
	"Kelpie",
	"Kenku",
	"Kettlesteam the Kenku",
	"Keyhole Dragonite",
	"Keyleth, Voice of the Tempest",
	"Kezai",
	"Khargra",
	"Khargra",
	"Khodumodumo",
	"Ki-Rin",
	"Ki-Rin",
	"Kiddywidget",
	"Kikimora",
	"Killer Whale",
	"Killmoulis",
	"King Kobold",
	"King Paúl",
	"Kinnara",
	"Kirikari",
	"Kishi",
	"Kitsune",
	"Kivan",
	"Knight Ab-errant",
	"Knight of the Road",
	"Knight",
	"Knucklehead Trout",
	"Koalinth Sergeant",
	"Koalinth",
	"Kobold Alchemist",
	"Kobold Bully",
	"Kobold Bully",
	"Kobold Chieftain",
	"Kobold Dragonshield",
	"Kobold Dragonshield",
	"Kobold Hero",
	"Kobold Inventer",
	"Kobold Inventor",
	"Kobold Scale Sorcerer",
	"Kobold Scale Sorcerer",
	"Kobold Scale Sorcerer",
	"Kobold Shaman",
	"Kobold Soldier",
	"Kobold Spellclerk",
	"Kobold Trapsmith",
	"Kobold Vampire Spawn",
	"Kobold War Machine",
	"Kobold",
	"Kokabel, Angel of the Stars",
	"Kongamato",
	"Koralk (Harvester Devil)",
	"Korred",
	"Korred",
	"Korred",
	"Korrigan",
	"Koschei",
	"Kot Bayun",
	"Kozilek, the Butcher of Truth",
	"Kraghammer Goat-Knight",
	"Krake Spawn",
	"Kraken Hatchling",
	"Kraken Priest",
	"Kraken Priest",
	"Kraken",
	"Kraken",
	"Krampus",
	"Kraul Death Priest",
	"Kraul Warrior",
	"Kruthik Hive Lord",
	"Kryt",
	"Kulmking",
	"Kuo-toa Archpriest",
	"Kuo-toa Whip",
	"Kuo-toa",
	"Kurok-Spirit",
	"Kuunganisha",
	"Kysh",
	"Labyrinth Keeper",
	"Lady Illmarrow",
	"Lady in White",
	"Laeral Silverhand",
	"Laestrigonian Giant",
	"Lake Troll",
	"Lamassu",
	"Lambent Witchfyre",
	"Lamia",
	"Lampad",
	"Land Lamprey",
	"Langdedrosa Cyanwrath",
	"Lantern Beetle",
	"Lantern Dragonette",
	"Larval Starspawn",
	"Latrian Flayer",
	"Lava Child",
	"Lava Child",
	"Lava Keeper",
	"Lava Weird",
	"Lawmage",
	"Lazav",
	"Lazivik",
	"Leech Swarm",
	"Lemure",
	"Lemurfolk Greyfur",
	"Lemurfolk",
	"Leng Folk Thief",
	"Leng Necromancer",
	"Leng Spider",
	"Leng Spider",
	"Leonin Iconoclast",
	"Leonin",
	"Leonino",
	"Leshen",
	"Leshy",
	"Lesser Air Elemental",
	"Lesser Ash Elemental",
	"Lesser Boneneedle",
	"Lesser Death Dog",
	"Lesser Dust Elemental",
	"Lesser Earth Elemental",
	"Lesser Fire Crab",
	"Lesser Fire Elemental",
	"Lesser Ice Elemental",
	"Lesser Lightning Elemental",
	"Lesser Lunarchidna",
	"Lesser Magma Elemental",
	"Lesser Metal Elemental",
	"Lesser Mineral Elemental",
	"Lesser Mud Elemental",
	"Lesser Negativ Energy Elemental",
	"Lesser Positiv Energy Elemental",
	"Lesser Radiance Elemental",
	"Lesser Salt Elemental",
	"Lesser Scrag",
	"Lesser Shadow",
	"Lesser Smoke Elemental",
	"Lesser Star Spawn Emissary",
	"Lesser Steam Elemental",
	"Lesser Void Elemental",
	"Lesser Water Elemental",
	"Lesser Wood Elemental",
	"Leucrotta",
	"Leucrotta",
	"Leucrotta, Adult",
	"Leucrotta, Young",
	"Leviathan",
	"Leviathan",
	"Leviathan, Maw of the Seas",
	"Liara Portyr",
	"Library Automaton",
	"Lich (in lair)",
	"Lich Hound",
	"Lich",
	"Lichen Lich",
	"Light Cavalry",
	"Light Dragon Wyrmling",
	"Light Drake",
	"Lightning Golem",
	"Lightning Treant",
	"Likho",
	"Liminal Drake",
	"Lindwurm",
	"Lion",
	"Liondrake",
	"Lionwere",
	"Liosalfar",
	"Lithonnite",
	"Living Bigby's Hand",
	"Living Blade of Disaster",
	"Living Burning Hands",
	"Living Cloudkill",
	"Living Demiplane",
	"Living Doll",
	"Living Inseen Servant",
	"Living Iron Statue",
	"Living Lightning Bolt",
	"Living Shade",
	"Living Spellbook",
	"Living Star",
	"Living Wick",
	"Lizard King/Queen",
	"Lizard",
	"Lizardfolk Commoner",
	"Lizardfolk Monk",
	"Lizardfolk Render",
	"Lizardfolk Scaleshield",
	"Lizardfolk Shaman",
	"Lizardfolk Subchief",
	"Lizardfolk",
	"Locathah Hunter",
	"Locathah",
	"Locksmith",
	"Lonely Sorrowsworn",
	"Lord Zombie",
	"Lord of Vultures",
	"Lorehold Apprentice",
	"Lorehold Apprentice",
	"Lorehold Pledgemage",
	"Lorehold Pledgemage",
	"Lorehold Professor of Chaos",
	"Lorehold Professor of Chaos",
	"Lorehold Professor of Order",
	"Lorehold Professor of Order",
	"Lorelei",
	"Lost Minotaur",
	"Lost Sorrowsworn",
	"Lost Soul",
	"Lothar",
	"Lotus Golem",
	"Lou Carcolh",
	"Loup Garou",
	"Loxoda",
	"Luck Dragon",
	"Luck Leech",
	"Lunar Devil",
	"Lunarian",
	"Lurker",
	"Lymarien Swarm",
	"Lymarien",
	"Lynx Creatlach",
	"Lystrosaurus",
	"Mad Piper",
	"Madam Eva",
	"Maegera The Dawn Titan",
	"Mage Hunter Golem",
	"Mage Hunter",
	"Mage",
	"Magewright",
	"Magma Bear",
	"Magma Landshark",
	"Magma Mephit",
	"Magma Octopus",
	"Magma Ooze",
	"Magmin",
	"Magmoid",
	"Magnetic Elemental",
	"Mahoru",
	"Major Malleable",
	"Malakbel",
	"Male Steeder",
	"Malformed Kraken",
	"Mallqui",
	"Malphas",
	"Mammon",
	"Mammoth",
	"Mamura",
	"Manabane Scarab Swarm",
	"Manastorm Golem",
	"Mandragora",
	"Mandrake",
	"Mandrake, Great",
	"Mandriano",
	"Mandrill",
	"Manes",
	"Manggus",
	"Mangrove Treant",
	"Manshoon",
	"Mantari",
	"Manticore",
	"Manticore, Heart-Piercer",
	"Mantik",
	"Mantik's Barbed",
	"Mantrap",
	"Margoyle",
	"Mari Lwyd",
	"Marid",
	"Marilith",
	"Marlos Urnrayle (with Lair Actions)",
	"Marlos Urnrayle",
	"Marsh Dire",
	"Martial Arts Adept",
	"Martial Arts Adept",
	"Marut",
	"Marut",
	"Mary Greymalkin",
	"Mask Wight",
	"Masked Killer",
	"Masked Okkator",
	"Massive Malleable",
	"Master Adranach",
	"Master Ferrius Ironback",
	"Master Sage",
	"Master Thief",
	"Master Thief",
	"Master of Cruelties",
	"Master of Demon Mountain",
	"Master of Souls",
	"Master of the Five Spires",
	"Mastiff",
	"Mastodon",
	"Matriarch Serpentine Lamia",
	"Mature Dark Young",
	"Maurezhi",
	"Mavka",
	"Maw Demon",
	"Maw Demon",
	"Maw of Sekolah",
	"Mbielu",
	"Mead Archon",
	"Meazel",
	"Medusa",
	"Meenlock",
	"Megaloceros",
	"Megapede",
	"Mei Jiao Shou",
	"Meld",
	"Meletian Hoplite",
	"Meloon Wardragon",
	"Mephistopheles",
	"Mercion",
	"Merfolk Salvager",
	"Merfolk Stormcaller",
	"Merfolk",
	"Merregon",
	"Merrenoloth",
	"Merrenoloth",
	"Merrow Shallowpriest",
	"Merrow",
	"Metallic Greatwyrm",
	"Metallic Peacekeeper",
	"Metallic Warbler",
	"Metee-Kolen-Ol",
	"Mezzoloth",
	"Mi-Go Dimension Walker",
	"Mi-Go Lord",
	"Mi-Go Scientist",
	"Mi-Go Scout",
	"Mi-Go Soldier",
	"Mi-Go Spawnling",
	"Mi-Go Warrior",
	"Mi-Go Worker",
	"Mi-Go",
	"Michael McHowlett",
	"Midnight Peddler",
	"Might Sliver",
	"Miirym",
	"Millitaur",
	"Mimic Chair",
	"Mimic",
	"Mimic, Map",
	"Mind Drinker Vampire",
	"Mind Flayer Arcanist",
	"Mind Flayer Lich (Illithilich)",
	"Mind Flayer",
	"Mind Mage",
	"Mindrot Thrall",
	"Mindwitness",
	"Mineral Ooze",
	"Minor Malleable",
	"Minotaur Living Crystal Statue",
	"Minotaur Skeleton",
	"Minotaur",
	"Minsc and Boo!",
	"Mirager",
	"Miraj Vizann",
	"Miremal",
	"Mirror Hag",
	"Mirrorman",
	"Mirt",
	"Mister Light",
	"Mister Witch",
	"Mistress of Midnight Teeth",
	"Mite",
	"Mite",
	"Mithril Guard",
	"Mngwa",
	"Moderate Malleable",
	"Moghadam",
	"Mold Zombie",
	"Molliver",
	"Moloch",
	"Moloch",
	"Molydeus",
	"Molydues",
	"Monarch Skeleton",
	"Mongrelfolk",
	"Monkey King",
	"Monodrone",
	"Monolith Champion",
	"Monolith Footman",
	"Monstrous Crayfish",
	"Monstrous Peryton",
	"Montaron and the Laughing Skull",
	"Moon Drake",
	"Moon Nymph",
	"Moon Priestess",
	"Moon-Beast ",
	"Moon-Priest of Nyarlathotep",
	"Moon-Vassal of Nyarlathotep",
	"Moonchild Naga",
	"Moonkite",
	"Moonstone Dragon Wyrmling",
	"Moorbounder",
	"Mordakhesh",
	"Mordant Snare",
	"Morko",
	"Morkoth",
	"Morkoth",
	"Mormesk The Wraith",
	"Morphlit",
	"Morphoi",
	"Morvudd",
	"Moss Lurker",
	"Mother Hydra",
	"Mother Hydra",
	"Mountain Dryad",
	"Mountain Giant",
	"Mountain Goat",
	"Mountain Nymph",
	"Mountain Strider",
	"Mouse King",
	"Mouth of Grolantor",
	"Mr. Dory",
	"Mud Golem",
	"Mud Mephit",
	"Muiral",
	"Mule",
	"Mummy Lord (in lair)",
	"Mummy Lord",
	"Mummy Warrior",
	"Mummy of the Deep",
	"Mummy",
	"Murder Crow",
	"Murgrik",
	"Mustard Jelly",
	"Mutant Troll",
	"Mutant Troll",
	"Mwaxanaré",
	"Myconid Adult",
	"Myconid Sovereign",
	"Myconid Sprout",
	"Mydnari",
	"Myling",
	"Myr Battlesphere",
	"Myr",
	"Mytholabe",
	"Mythos Ghast",
	"Mythos Ghoul",
	"Mythos Satyr",
	"Môrgæn",
	"Nabassu",
	"Nabassu",
	"Nachzehrer",
	"Naergoth Bladelord",
	"Naes Inuus",
	"Nagpa",
	"Nagpa",
	"Naiad",
	"Naina (in Humanoid form)",
	"Naina",
	"Naizu-Ha",
	"Nalfeshnee",
	"Nalusa Falaya",
	"Narrak",
	"Narshark",
	"Narzugon",
	"Narzugon",
	"Nass Lantomir's Ghost",
	"Nauk",
	"Nechrichor",
	"Necromancer Wizard",
	"Necromancer",
	"Necromancer",
	"Necromite of Myrkul",
	"Necrophage Ghast",
	"Necrotic Slime",
	"Necrotic Tick",
	"Needle Blight",
	"Needle Lord",
	"Needle Spawn",
	"Neo-Otyugh",
	"Neogi Hatchling",
	"Neogi Master",
	"Neogi Master",
	"Neogi",
	"Neophron",
	"Neothelid",
	"Nephirron Devil",
	"Nereid",
	"Nergaliid",
	"Neronvain",
	"Nezahal, Primal Tide",
	"Nezznar The Black Spider",
	"Ngobou",
	"Nharyth",
	"Nian",
	"Nichny",
	"Night Blade",
	"Night Hag",
	"Night Scorpion",
	"Night-Gaunt",
	"Nightgarm",
	"Nightgaunt",
	"Nightgaunt",
	"Nightmare Shepherd",
	"Nightmare Troll",
	"Nightmare",
	"Nightveil Specter",
	"Nightwalker",
	"Nightwalker",
	"Nihilethic Zombie",
	"Nilbog",
	"Nilbog",
	"Nimblewright",
	"Ningyo",
	"Nintra Siotta",
	"Niv-Mizzet",
	"Nivix Cyclops",
	"Nix Riversong",
	"Nkosi Pridelord",
	"Nkosi",
	"Noble",
	"Noctiny",
	"Nodosaurus",
	"Norker War Leader",
	"Norker",
	"Nosferatu",
	"Noth-Norren",
	"Nothic",
	"Nupperibo",
	"Nupperibo",
	"Nycaloth",
	"Nyctli Swarm",
	"Nyctli",
	"Nyogtha Body",
	"Nyx-Fleece Ram",
	"Oak Truestrike",
	"Oaken Bolter",
	"Oasis Keeper",
	"Oblex Spawn",
	"Obsessed Artist",
	"Obzedat Ghost",
	"Oceanus (Sea Elf)",
	"Ochre Jelly",
	"Octopus",
	"Oculo Swarm",
	"Ogre 'Big Boss'",
	"Ogre Battering Ram",
	"Ogre Battering Ram",
	"Ogre Bolt Launcher",
	"Ogre Chain Brute",
	"Ogre Howdah",
	"Ogre Howdah",
	"Ogre Skeleton",
	"Ogre Zombie",
	"Ogre",
	"Ogrepede",
	"Ogrillon Sellsword",
	"Ogrillon Warmage",
	"Ogrémoch",
	"Oinoloth",
	"Oinoloth",
	"Okkator Assassin",
	"Old Leng Spider",
	"Olhydra",
	"Oliphaunt",
	"Olive Slime Zombie",
	"Olive Slime",
	"Omin Dran",
	"One-Eyed Shiver",
	"One-Headed Clockwork Dragon",
	"One-Horned Ogre",
	"Oni",
	"Onyx Magistrate",
	"Oozasis",
	"Ooze Master",
	"Ooze-Folk",
	"Ophanim",
	"Ophidiotaur",
	"Ophinix",
	"Ophio Fungus",
	"Oracle of Strixhaven",
	"Oracle",
	"Orc Acolyte",
	"Orc Berserker",
	"Orc Berserker",
	"Orc Blackguard",
	"Orc Blade of Ilneval",
	"Orc Brute",
	"Orc Champion",
	"Orc Claw of Luthic",
	"Orc Cutthroat",
	"Orc Demonologist",
	"Orc Eye of Gruumsh",
	"Orc Fire Eater",
	"Orc Hand of Gruumsh",
	"Orc Hand of Yurtrus",
	"Orc Hunter",
	"Orc Marauder",
	"Orc Mystic",
	"Orc Necromancer",
	"Orc Nurtured One of Yurtrus",
	"Orc Occultist",
	"Orc Peon",
	"Orc Raid Chief",
	"Orc Ranger",
	"Orc Red Fang of Shargaas",
	"Orc Scout",
	"Orc Shaman",
	"Orc Thug",
	"Orc War Chief",
	"Orc Warlock",
	"Orc Warrior",
	"Orc",
	"Orcus",
	"Orcus",
	"Oread",
	"Oreioth",
	"Origami Warrior",
	"Oriq Blood Mage",
	"Oriq Recruiter",
	"Orniraptor",
	"Orobas Devil",
	"Orog",
	"Orphan of the Black",
	"Orthon",
	"Orthon",
	"Orthrus",
	"Ortifex",
	"Orzhov Giant",
	"Ostinato",
	"Oth",
	"Otterfolk",
	"Otyugh",
	"Ouroban",
	"Ouroboros",
	"Outer Abomination",
	"Outer Mutant Priest of Yog-Sothoth",
	"Outer Mutant Scout",
	"Outer Spawn",
	"Overshadow",
	"Owl Harpy",
	"Owl",
	"Owlbear Matron",
	"Owlbear",
	"Owlwere",
	"Ox",
	"Pact Devil",
	"Pact Drake",
	"Pact Lich",
	"Paige Truestrike",
	"Pal-Rai-Yuk",
	"Pale Screamer",
	"Panther",
	"Paper Drake",
	"Paper Golem Swarm",
	"Paper Golem",
	"Parasite Infested Behir",
	"Parzelon, King of Secrets",
	"Parzz'val",
	"Past Yithian",
	"Pattern Dancer",
	"Pazuzu",
	"Peat Mammoth",
	"Pech Lithlord",
	"Pech Stonemaster",
	"Pech",
	"Pech",
	"Pegasus",
	"Peluda Drake",
	"Pelyious Avhoste",
	"Pendragon Beestinger",
	"Pentadrone",
	"Percival de Rolo",
	"Peryton",
	"Pest Mascot",
	"Pestie Mite",
	"Pestilence Swarm",
	"Phaerimm",
	"Phantom Warrior",
	"Phantom",
	"Pharblex Spattergoo",
	"Phase Giant",
	"Phase Spider",
	"Phelddagrif",
	"Philosopher's Ghost",
	"Phoenix Anvil",
	"Phoenix",
	"Phoenix",
	"Phycomid",
	"Phylaskia",
	"Piasa",
	"Pidlwick II",
	"Piercer",
	"Pike Trickfoot",
	"Pillar of the Lost Magocracy",
	"Pine Doom",
	"Pirate Axe Thrower",
	"Pirate Bosun",
	"Pirate Captain",
	"Pirate Chain Swinger",
	"Pirate Deck Wizard",
	"Pirate First Mate",
	"Pishacha",
	"Pit Fiend",
	"Pixie",
	"Pixie's Umbrella",
	"Pixiu",
	"Plague Spirit",
	"Plaguebringer",
	"Plainscow",
	"Planetar",
	"Plaresh",
	"Plasmid",
	"Platinum Golem",
	"Plesiosaurus",
	"Podling",
	"Poena, Duke of Retribution",
	"Poisonous Fire Snake",
	"Poisonous Snake",
	"Polar Bear",
	"Pollenella the Honeybee",
	"Polukranos",
	"Pombero",
	"Pony",
	"Portentia Dran",
	"Possessed Pillar",
	"Poultice Sliver",
	"Precognitive Mage",
	"Preta",
	"Priest of Blight",
	"Priest of Osybus",
	"Priest",
	"Primal Oozer",
	"Primeval Titan",
	"Prismari Apprentice",
	"Prismari Apprentice",
	"Prismari Pledgemage",
	"Prismari Pledgemage",
	"Prismari Prof. of Expression",
	"Prismari Prof. of Expression",
	"Prismari Prof. of Perfection",
	"Prismari Prof. of Perfection",
	"Prismatic Beetle Swarm",
	"Proto-Shoggoth",
	"Pseudodragon",
	"Psoglav",
	"Psychic Vampire",
	"Pterafolk",
	"Pteranodon",
	"Pumpkin King",
	"Pumpkin King",
	"Purple Slime",
	"Purple Worm",
	"Purple Wormling",
	"Pustulent Shambler",
	"Pustuloid",
	"Putrescent Slime",
	"Putrid Haunt",
	"Pyrolisk",
	"Qiqirin",
	"Qithukye",
	"Quadricorn",
	"Quadrone",
	"Quaggoth Spore Servant",
	"Quaggoth Thonot",
	"Quaggoth",
	"Quandrix Apprentice",
	"Quandrix Apprentice",
	"Quandrix Pledgemage",
	"Quandrix Pledgemage",
	"Quandrix Prof. of Substance",
	"Quandrix Prof. of Substance",
	"Quandrix Prof. of Theory",
	"Quandrix Prof. of Theory",
	"Quasit",
	"Queen Asria",
	"Queen of Birds",
	"Queen of Cats",
	"Queen of Scorpions",
	"Queen of Serpents",
	"Quetzalcoatlus",
	"Quickling",
	"Quickserpent",
	"Quickstep",
	"Quickwood",
	"Quiet Soul",
	"Quipper",
	"Quoreq",
	"Qwyllion",
	"Radiant Idol",
	"Radiant Spark Swarm",
	"Rageipede",
	"Rahadin",
	"Raider's Worg",
	"Rak Tulkhesh",
	"Rakdos Lampooner",
	"Rakdos Performer",
	"Rakdos",
	"Rakshasa",
	"Ram Sugar",
	"Ramag Portal Master",
	"Ramag",
	"Rangda, Demon Lord of Witches",
	"Ras Nsi",
	"Rat Hermit",
	"Rat King",
	"Rat",
	"Ratatosk Warlord",
	"Ratatosk",
	"Ratfolk Mercenary",
	"Ratfolk Rogue",
	"Ratfolk Warlock",
	"Ratfolk",
	"Rath Modar",
	"Rathar",
	"Rattok",
	"Ravager Slaughter Lord",
	"Ravager Stabby-Stabber",
	"Raven",
	"Ravenala",
	"Ravenfolk Doom Croaker",
	"Ravenfolk Scout",
	"Ravenfolk Warrior",
	"Ravenous Wendigo",
	"Razerblast",
	"Razorleaf",
	"Re-Animated Guard",
	"Re-Animated Laborer",
	"Re-Animated Soldier",
	"Reaper of Bhaal",
	"Reckoner",
	"Red Abishai",
	"Red Abishai",
	"Red Dracolisk",
	"Red Dragon Wyrmling",
	"Red Hag",
	"Red Jester",
	"Red Slaad",
	"Red-Banded Line",
	"Redbrand Ruffian",
	"Redcap",
	"Redcap",
	"Reef Shark",
	"Relentless Juggernaut",
	"Relentless Slasher",
	"Relic Sloth",
	"Remallia Haventree",
	"Remnant Chosen",
	"Remnant Cultist",
	"Remorhaz",
	"Repository",
	"Resinous Frog",
	"Retriever",
	"Returned Drifter",
	"Returned Palamnite",
	"Returned Sentry",
	"Revenant",
	"Reynard",
	"Rezmir",
	"Rhan-Tegoth",
	"Rhinoceros",
	"Rhopalocerex, Demon Lord of Deception",
	"Rictavio",
	"Riding Horse",
	"Rift Swine",
	"Righteous Sentinel",
	"Rime Worm Grub",
	"Ring Servant",
	"Ringlerun",
	"Rip Tide Priest",
	"Risen Reaver",
	"Risen Warlock",
	"Rivermaw Brawler",
	"Rivermaw Stormborn",
	"Roach",
	"Roachling Lord",
	"Roachling Scout",
	"Roachling Skirmisher",
	"Roc",
	"Rock Roach",
	"Rock Troll",
	"Roggenwolf",
	"Ronus",
	"Rootling",
	"Roper",
	"Rosie Beestinger",
	"Rot Troll",
	"Rot Troll",
	"Rothorror",
	"Rotsam Swarm",
	"Rotsam",
	"Rotter",
	"Rotting Wind",
	"Rubblebelt Stalker",
	"Rubezahl",
	"Ruby Ooze",
	"Rug of Smothering",
	"Ruin Grinder",
	"Ruin",
	"Rum Gremlin",
	"Rum Lord",
	"Runeswarm",
	"Rusalka",
	"Rusalka",
	"Russet Mold",
	"Rust Drake",
	"Rust Monster",
	"Rutterkin",
	"Ryven",
	"Saber-Toothed Tiger",
	"Sacred Statue",
	"Sacred Statue",
	"Sacred Stone Monk",
	"Saemon Havarian",
	"Sage",
	"Sahuagin Baron",
	"Sahuagin Blademaster",
	"Sahuagin Champion",
	"Sahuagin Coral Smasher",
	"Sahuagin Deep Diver",
	"Sahuagin Hatchling Swarm",
	"Sahuagin High Priestess",
	"Sahuagin Priestess",
	"Sahuagin Warlock of Uk'otoa",
	"Sahuagin Wave Shaper",
	"Sahuagin",
	"Salamander Monarch",
	"Salamander",
	"Salt Devil",
	"Salt Golem",
	"Sammael",
	"Sanbalet",
	"Sand Hag",
	"Sand Silhouette",
	"Sand Spider",
	"Sanddrift Drake",
	"Sandling",
	"Sandman",
	"Sandwyrm",
	"Sane",
	"Sap Demon",
	"Sapphire Dragon Wyrmling",
	"Sapphire Jelly",
	"Sapphire Sentinel",
	"Sarcophagus Slime",
	"Sarevok",
	"Sarsaok",
	"Sasori Fukurowashi",
	"Sasquatch",
	"Satarre Destroyer",
	"Satarre Mystic",
	"Sathaq Worm",
	"Satyr Reveler",
	"Satyr Thornbearer",
	"Satyr",
	"Savage Orc",
	"Savager",
	"Scaladar",
	"Scanlan Shorthalt",
	"Scarecrow",
	"Scarlet Ibis",
	"Scheznyki",
	"Scholar Brain Cylinder",
	"Scion of Chaugnar Faugn",
	"Scitalis",
	"Scopikis",
	"Scorchbringer Guard",
	"Scorpion Assassin",
	"Scorpion Cultist",
	"Scorpion",
	"Scourge",
	"Scout",
	"Screaming Devilkin",
	"Screaming Devilkin",
	"Screecher",
	"Scribe Devil",
	"Scrofin",
	"Scroll Mummy",
	"Scythe Tree",
	"Sea Dragon Qyrmling",
	"Sea Fury",
	"Sea Hag",
	"Sea Horse",
	"Sea Lion",
	"Sea Spawn",
	"Seafallen Captain",
	"Seafallen Crew",
	"Seafallen Host",
	"Seal",
	"Selachian",
	"Selang",
	"Selenelion Twin",
	"Sema",
	"Sentinel in Darkness",
	"Seodra",
	"Sepulchral Guardian",
	"Sergeant",
	"Serpentfolk Alchemist",
	"Serpentfolk of Yig",
	"Serpentfolk",
	"Serpentine Lamia",
	"Serpopard",
	"Serpopard",
	"Servant of Yig",
	"Servant of the Unsated God",
	"Servant of the Vine",
	"Servitor Thrull",
	"Servitor of the Outer Gods",
	"Servo",
	"Setessan Hoplite",
	"Severin",
	"Shabti",
	"Shadar-Kai Gloom Weaver",
	"Shadar-Kai Shadow Dancer",
	"Shadar-Kai Soul Monger",
	"Shadhavar",
	"Shadow Assassin",
	"Shadow Beast",
	"Shadow Blight",
	"Shadow Boxer",
	"Shadow Demon",
	"Shadow Elemental",
	"Shadow Fey Ambassador",
	"Shadow Fey Elves",
	"Shadow Fey Poisoner",
	"Shadow Giant",
	"Shadow Goblin",
	"Shadow Horror",
	"Shadow Mastiff Alpha",
	"Shadow Mastiff",
	"Shadow Mastiff",
	"Shadow Ooze",
	"Shadow Rat",
	"Shadow River Lord",
	"Shadow Skeleton",
	"Shadow Troll",
	"Shadow of Death",
	"Shadow",
	"Shadowgast",
	"Shadowtouched Umberhulk",
	"Shadrix Silverquill",
	"Shambling Mound",
	"Shantak",
	"Shantak",
	"Shard Swarm",
	"Sharkjaw Skeleton",
	"Sharwyn Hucrele",
	"Shell Shark",
	"Shellycoat",
	"Shemshime",
	"Shield Guardian",
	"Shifter",
	"Shiftshroom",
	"Shimmer Seal",
	"Shipbreaker Sea Serpent",
	"Shippei-Tao",
	"Shoalar Quaderil",
	"Shoalar Quanderil",
	"Shoggoth",
	"Shoggoth",
	"Shoggoth",
	"Shoosuva",
	"Shoosuva",
	"Shoreline Scrapper",
	"Shriekbat",
	"Shrieker",
	"Shroom",
	"Shroud",
	"Shukankor",
	"Shurale",
	"Sibriex",
	"Sibriex",
	"Sigilian",
	"Sildar Hallwinter",
	"Silenal",
	"Silver Dragon Wyrmling Skeleton",
	"Silver Dragon Wyrmling",
	"Silver Knight",
	"Silverpaw Dog",
	"Silverpaw Paladin",
	"Silverquill Apprentice",
	"Silverquill Apprentice",
	"Silverquill Pledgemage",
	"Silverquill Pledgemage",
	"Silverquill Prof. of Radiance",
	"Silverquill Prof. of Radiance",
	"Silverquill Prof. of Shadow",
	"Silverquill Prof. of Shadow",
	"Simhamukha",
	"Simurg",
	"Sir Breaford",
	"Sir Redar, Knight of the Secret Oath",
	"Sir Ursas",
	"Sire of Insanity",
	"Sire of Stagnation",
	"Siren",
	"Sirene",
	"Skabatha Nightshade",
	"Skeemo Weirdbottle",
	"Skein Witch",
	"Skeletal Alchemist",
	"Skeletal Giant Owl",
	"Skeletal Juggernaut",
	"Skeletal Owlbear",
	"Skeletal Polar Bear",
	"Skeletal Swarm",
	"Skeletal Titan",
	"Skeletal Two-Headed Owlbear",
	"Skeleton Lord",
	"Skeleton Warrior",
	"Skeleton Warrior",
	"Skeleton",
	"Skelzi",
	"Skin Bat",
	"Skitterhaunt",
	"Skittering Horro",
	"Skitterwidget",
	"Skulk",
	"Skulk",
	"Skulk",
	"Skull Drake",
	"Skull Lantern",
	"Skull Lasher of Myrkul",
	"Skull Lord",
	"Skull Lord",
	"Skum",
	"Sky Leviathan",
	"Skyjek Roc",
	"Skylla",
	"Skyswimmer",
	"Skyweaver",
	"Slaad Tadpole",
	"Sleipnir",
	"Slime Mold",
	"Slithering Tracker",
	"Slithering Tracker",
	"Slithering Tracker",
	"Sliver Queen",
	"Sliver",
	"Slow Storm",
	"Sluagh Swarm",
	"Smaragdine Golem",
	"Smoke Mephit",
	"Smolder Souleater",
	"Snake with a Hundred Mage Hands",
	"Sniffer Beetle",
	"Snow Cat",
	"Snow Giant",
	"Snow Golem",
	"Snow Hag",
	"Snow Leopard",
	"Snow Spider",
	"Snow Terror",
	"Solar",
	"Soldier",
	"Somberweave",
	"Son of Fenris",
	"Song Angel",
	"Sooze",
	"Sorcerer Brain Cylinder",
	"Soul Eater",
	"Soul Monger",
	"Soul Reaper",
	"Spark",
	"Spawn of Akyishigal",
	"Spawn of Alquam",
	"Spawn of Arbeyach",
	"Spawn of Chernobog",
	"Spawn of Hriggala",
	"Spawn of Kyuss",
	"Spawn of Parzelon",
	"Spawn of Rhopalocerex",
	"Speaker to the Darkness",
	"Spectator",
	"Specter (poltergeist)",
	"Specter",
	"Spectral Guardian",
	"Spectral Troll",
	"Spellhound",
	"Spellskite",
	"Sperm Whale",
	"Sperman",
	"Spider Drake",
	"Spider Skull",
	"Spider Thief",
	"Spider of Leng",
	"Spider",
	"Spined Devil",
	"Spinosaurus",
	"Spire Walker",
	"Spirit Lamp",
	"Spirit Naga",
	"Spirit Statue Mascot",
	"Spirit Troll",
	"Spirit",
	"Spitting Mimic",
	"Spitting Sea Serpent",
	"Spitting Sliver",
	"Splugoth the Returned",
	"Sporous Crab",
	"Spree",
	"Spring Eladrin",
	"Spring Eladrin",
	"Sprite",
	"Spurred Water Skate",
	"Spy",
	"Squirt the Oilcan",
	"Ssadar",
	"Ssendam, Lord of Madness",
	"Stahnk (Undead Beast)",
	"Star Drake",
	"Star Spawn Grue",
	"Star Spawn Hulk",
	"Star Spawn Larva Mage",
	"Star Spawn Larve Mage",
	"Star Spawn Mangler",
	"Star Spawn Seer",
	"Star Spawn Seer",
	"Star Vampire",
	"Star Vampire",
	"Star-Spawn of Cthulhu",
	"Starspawn",
	"Steam Golem",
	"Steam Mephit",
	"Steel Crane",
	"Steel Leaf Kavu",
	"Steel Predator",
	"Steel Predator",
	"Stegocentipede",
	"Stegosaurus",
	"Stellar Rorqual",
	"Stench Kow",
	"Stirge",
	"Stolos",
	"Stone Creeper",
	"Stone Cursed",
	"Stone Cursed",
	"Stone Defender",
	"Stone Giant Dreamwalker",
	"Stone Giant",
	"Stone Golem",
	"Stone Guardian Golem",
	"Stone Juggernaut",
	"Stone Strix",
	"Stonemelder",
	"Storm Giant Quintessent",
	"Storm Giant Quintessent",
	"Storm Giant Skeleton",
	"Storm Giant",
	"Storm Lord",
	"Storm Maiden",
	"Storm Spirit",
	"Stormboar",
	"Strahd Von Zarovich",
	"Strahd Zombie",
	"Strahd's Animated Armor",
	"Strangle Weed",
	"Strigoi",
	"Strixhaven Campus Guide",
	"Strobing Fungus",
	"Strongheart",
	"Stryx",
	"Stuhac",
	"Stygian Fat-Tailed Scorpion",
	"Stygian Skeleton",
	"Su-Monster",
	"Subek",
	"Succubus",
	"Sul Khatesh",
	"Suldil Baldoriel",
	"Sulsha",
	"Summer Eladrin",
	"Summer Eladrin",
	"Sunbird",
	"Sunder Shaman",
	"Sunset Raptor",
	"Suppurating Ooze",
	"Suturefly",
	"Svirfneblin",
	"Swamp Adder",
	"Swamp Lily",
	"Swamp Naga",
	"Swampgas Bubble",
	"Swarm of Animated Books",
	"Swarm of Bats",
	"Swarm of Bees",
	"Swarm of Campestris",
	"Swarm of Centipedes",
	"Swarm of Compsognathus",
	"Swarm of Cranium Rats",
	"Swarm of Cranium Rats",
	"Swarm of Esteron",
	"Swarm of Gremishkas",
	"Swarm of Hoard Scarabs",
	"Swarm of Insects",
	"Swarm of Maggots",
	"Swarm of Poisonous Snakes",
	"Swarm of Quippers",
	"Swarm of Rats",
	"Swarm of Ravens",
	"Swarm of Rot Grubs",
	"Swarm of Rot Grubs",
	"Swarm of Scarabs",
	"Swarm of Squirrels",
	"Swarm of Zombie Limbs",
	"Swashbuckler",
	"Swavain Basilisk",
	"Swolbold",
	"Sword Spider",
	"Sword Wraith Commander",
	"Sword Wraith Commander",
	"Sword Wraith Warrior",
	"Sylvan Stalker",
	"Tabaxi Hunter",
	"Tabaxi Minstrel",
	"Tabaxi",
	"Taer",
	"Tai Feng",
	"Talis The White",
	"Tanarukk",
	"Tanazir Quandrix",
	"Tangtal",
	"Tar Ghoul",
	"Tar Ooze",
	"Tarkanan Assassin",
	"Tarkun the Dessicated",
	"Tarnhem",
	"Tarrasque",
	"Tarul Var",
	"Taryon Darrington",
	"Tashlyn Yafeera",
	"Tasloi Sniper",
	"Tasloi",
	"Tazelwurm",
	"Technothug",
	"Tecuziztecatl",
	"Tembril",
	"Temple Dog",
	"Temporal Crawler",
	"Tendriculos",
	"Tendril Puppet",
	"Tentacled Horror",
	"Tentaghoul",
	"Teratashia",
	"Terror Bird",
	"Tetomatli",
	"Tetzimoc, Primal Death",
	"Thalasskoptis",
	"Thayan Apprentice",
	"Thayan Warrior",
	"The Bloated Woman",
	"The Curator, Hell's Collector",
	"The Dark Demon",
	"The Filth",
	"The Forest Queen",
	"The Forgotten Prince",
	"The Haunter",
	"The Holwer",
	"The Hungry",
	"The King in Yellow",
	"The Lord of Blades",
	"The Lost",
	"The Pudding King",
	"The Shadow Pharaoh",
	"Theran Chimera",
	"Thessalar",
	"Thessalar's Homunculus",
	"Thessalheart Construct",
	"Thessalhydra",
	"Thessalkraken",
	"Theullai",
	"Thief Lord",
	"Thin Giant",
	"Tho-Tcho",
	"Thorn Slinger",
	"Thorned Sulfurlord",
	"Thornheart Guardian",
	"Thorny Vegepygmy",
	"Thought Spy",
	"Thousand Teeth",
	"Thrall of Yog-Sothoth",
	"Thread-Bound Constrictor Snake",
	"Three-Headed Clockwork Dragon",
	"Three-Headed Cobra",
	"Thri-Kreen",
	"Thrummren",
	"Thug",
	"Thurl Merosska",
	"Thursir Giant",
	"Tiamat",
	"Tiberius Inuus",
	"Tidehunter",
	"Tiefling Muralist",
	"Tiger",
	"Timeless Chronomancer",
	"Timingila",
	"Titanoboa",
	"Titivilus",
	"Titivilus",
	"Tlincalli",
	"Toad King",
	"Tomb Tapper",
	"Topaz Dragon Wyrmling",
	"Tophet",
	"Topi",
	"Tormented Qiqirin",
	"Tortle Druid",
	"Tortle Druid",
	"Tortle",
	"Tortle",
	"Tosculi Drone",
	"Tosculi Elite Bow Raider",
	"Tosculi Hive Queen",
	"Tosculi Jeweled Drone",
	"Tosculi Warrior",
	"Totivillus, Scribe of Hell",
	"Transcendent Lunarchidna",
	"Transmuter Wizard",
	"Transmuter",
	"Trapper",
	"Trapper",
	"Treacle",
	"Treant Sapling",
	"Treant",
	"Tree Blight",
	"Tree Skinner",
	"Tressym",
	"Tri-Flower Frond",
	"Tri-Flower Frond",
	"Tribal Warrior",
	"Tricenatorus",
	"Triceratops",
	"Tridrone",
	"Trinket",
	"Triton Master of Waves",
	"Triton Shorestalker",
	"Troglodyte Champion of Laogzed",
	"Troglodyte",
	"Troll Boar",
	"Troll Runt",
	"Troll",
	"Trollkin Grunt",
	"Trollkin Reaver",
	"Trollkin Shaman",
	"Trollkin",
	"Tromokratis",
	"Trostani",
	"Truesong Dancer",
	"Truesong Dirge",
	"Tsucora Quori",
	"Tulpa",
	"Tunnel Prawn",
	"Tunnel Worm",
	"Tusk Giant",
	"Tuskaloth",
	"Tusked Crimson Ogre",
	"Tusked Skyfish",
	"Tveirherjar",
	"Twig Blight",
	"Two-Headed Cerberus",
	"Two-Headed Crocodile",
	"Two-Headed Eagle",
	"Two-Headed Owlbear",
	"Two-headed Troll",
	"Typhon",
	"Typhon, Father of Monsters",
	"Tyrannosaurus Rex",
	"Tyrannosaurus Zombie",
	"Tzepharion",
	"Udaak",
	"Ulamog, the Ceaseless Hunger",
	"Ulitharid",
	"Ulitharid",
	"Ulnorya",
	"Ulthar Champion",
	"Ultralisk",
	"Ultroloth",
	"Umber Hulk",
	"Umbral",
	"Un-Man",
	"Undead Phoenix",
	"Undead Sharkenbear",
	"Undead Warchief",
	"Undercity Medusa",
	"Underworld Cerberus",
	"Undine",
	"Undying Councilor",
	"Undying Soldier",
	"Unhatched",
	"Unicorn",
	"Unspeakable Horror",
	"Uraeus",
	"Urbane Magician",
	"Urdimmu",
	"Urochar (strangling Watcher)",
	"Ursa Polaris",
	"Ushabti",
	"Uthgardt Shaman",
	"Vaettir",
	"Valaara",
	"Valenar Hawk",
	"Valenar Hound",
	"Valenar Steed",
	"Valin Sarnaster",
	"Valkruung",
	"Valkyrie",
	"Vallowex",
	"Valygar",
	"Vampire (spellcaster)",
	"Vampire (warrior)",
	"Vampire Neonate",
	"Vampire Patrician",
	"Vampire Priestess",
	"Vampire Rose",
	"Vampire Spawn",
	"Vampire Thrall",
	"Vampire Warlock",
	"Vampire",
	"Vampiric Ixitxachitl Cleric",
	"Vampiric Ixitxachitl",
	"Vampiric Jade Statue",
	"Vampiric Knight",
	"Vampiric Mind Flayer",
	"Vampiric Mist",
	"Vanara",
	"Vangsluagh",
	"Vanifer (with Lair Actions)",
	"Vanifer",
	"Vapor Lynx",
	"Vargouille",
	"Vargouille",
	"Varjra Safahr",
	"Varnyr",
	"Vegepygmy Chief",
	"Vegepygmy Chief",
	"Vegepygmy Commoner/Worker",
	"Vegepygmy Guard",
	"Vegepygmy",
	"Vellin Farstride",
	"Vellso",
	"Vellyne Harpell",
	"Velociraptor",
	"Velomachus Lorehold",
	"Venom Elemental",
	"Venom Maw Hydra",
	"Venom Troll",
	"Venom Troll",
	"Venomous Mummy",
	"Vent Linnorm",
	"Verbeeg Longstrider",
	"Verbeeg Marauder",
	"Verdalin",
	"Vesiculosa",
	"Veteran Swordbreaker Skeleton",
	"Veteran",
	"Vex'ahlia",
	"Vexxeh",
	"Viari",
	"Vicious Blood Hawk",
	"Viconia DeVir",
	"Victoro Cassalanter",
	"Viiret",
	"Viktor",
	"Vila",
	"Vile Barber (Siabhra)",
	"Vine Blight",
	"Vine Drake",
	"Vine Golem",
	"Vine Lord",
	"Vine Terror",
	"Vine Troll Skeleton",
	"Vines of Nemthyr",
	"Violet Fungus",
	"Virtuoso Lich",
	"Virulent Sliver",
	"Vladimir Horngaard",
	"Vodyanoy",
	"Void Cultist",
	"Void Dragon Wyrmling",
	"Void Giant",
	"Void Speaker",
	"Voidling",
	"Voidpool",
	"Voidwracked Mage",
	"Volothamp 'Volo' Geddarm",
	"Volt",
	"Voonith",
	"Vorin",
	"Vos'skyriss Serpentfolk Ghost",
	"Vos'skyriss Serpentfolk",
	"Vrock",
	"Vulchling",
	"Vulture",
	"Walking Statue of Waterdeep",
	"Walled Horror",
	"Walnut Dankgrass",
	"Walrus",
	"Wamp",
	"Wampus Cat",
	"Wanyudo",
	"War Chaplain",
	"War Machine Golem",
	"War Mage",
	"War Ostrich",
	"War Pig",
	"War Priest",
	"War Priest",
	"War Priest",
	"War Titan",
	"War Troll",
	"War Wyvern",
	"War",
	"Wardu",
	"Warduke",
	"Warforged Colossus",
	"Warforged Soldier",
	"Warforged Titan",
	"Warhorse Skeleton",
	"Warhorse",
	"Warlock of the Archfey",
	"Warlock of the Archfey",
	"Warlock of the Fiend",
	"Warlock of the Fiend",
	"Warlock of the Great Old One",
	"Warlock of the Great Old One",
	"Warlock's Trumpetbloom",
	"Warlord",
	"Warmth Thief",
	"Wasteland Dragon Wyrmling",
	"Wastrilith",
	"Water Elemental Myrmidon",
	"Water Elemental Myrmidon",
	"Water Elemental",
	"Water Horse",
	"Water Leaper",
	"Water Weird",
	"Weasel",
	"Web Troll",
	"Weeping Treant",
	"Weirding Scroll",
	"Wendigo",
	"Were-Mist",
	"Werebat",
	"Werebat",
	"Werebear",
	"Wereboar",
	"Weredactyl",
	"Werehyena",
	"Wererat",
	"Wereraven",
	"Wereshark",
	"Weretiger",
	"Werewolf (Krallenhorde)",
	"Werewolf Alpha",
	"Werewolf",
	"Werewowl",
	"Werynax",
	"Wharfling Swarm",
	"Wharfling",
	"Whisperer in Darkness",
	"White Abishai",
	"White Abishai",
	"White Ape",
	"White Dracolisk",
	"White Dragon Wyrmling",
	"White Maw",
	"White Stag",
	"Whymsee (Kraken Priest Variant)",
	"Wicked Skull",
	"Wickerman",
	"Widow Creeper",
	"Wiggan Nettlebee",
	"Wight Walker",
	"Wight",
	"Will-o-wisp",
	"Willowhaunt",
	"Wind Demon",
	"Wind Dragon Wyrmling",
	"Wind Eater",
	"Wind Weasel",
	"Wind's Harp",
	"Windharrow",
	"Windwalker Wendigo",
	"Windy Wailer",
	"Winged Ape",
	"Winged Bull",
	"Winged Kobold",
	"Winged Lion",
	"Winged Sliver",
	"Winged Thrull",
	"Winter Eladrin",
	"Winter Eladrin",
	"Winter Sprite",
	"Winter Wolf",
	"Winterghast",
	"Wintergrim",
	"Wirbeln Fungi",
	"Witch Grass",
	"Witch Queen",
	"Witch of the Woods",
	"Witchlight Hands",
	"Witchlight Hands",
	"Witchlight",
	"Witherbloom Apprentice",
	"Witherbloom Apprentice",
	"Witherbloom Pledgemage",
	"Witherbloom Pledgemage",
	"Witherbloom Prof. of Decay",
	"Witherbloom Prof. of Decay",
	"Witherbloom Prof. of Growth",
	"Witherbloom Prof. of Growth",
	"Witherstench",
	"Wizard Kobold",
	"Woe Siphon",
	"Woe Strider",
	"Wolf Reaver Dwarf",
	"Wolf Spirit Swarm",
	"Wolf",
	"Wolfwere Alpha",
	"Wolfwere",
	"Wolfwere",
	"Wolpertinger",
	"Wood Elf Wizard",
	"Wood Golem",
	"Wood Ward",
	"Wood Woad",
	"Wood Woad",
	"Wooden Golem",
	"Woodwose",
	"Woolly Rhinoceros",
	"Worg",
	"Worm of Ghroth",
	"Wormhearted Suffragan",
	"Wraith Bear",
	"Wraith",
	"Wraithroot Tree",
	"Wretched Sorrowsworn",
	"Wurm",
	"Wyvern Knight",
	"Wyvern",
	"Wyvern-Rider",
	"Xan Moonblade",
	"Xandala",
	"Xanka",
	"Xardorok Sunblight",
	"Xenabsorber",
	"Xhkarsh",
	"Xill",
	"Xing Tian",
	"Xiphus",
	"Xorn",
	"Xvart Warlock of Raxivort",
	"Xvart Warlock of Raxivort",
	"Xvart",
	"Xvart",
	"Xzar the Chaos Clone",
	"Yaga Goo",
	"Yagnoloth",
	"Yakfolk Priest",
	"Yakfolk Warrior",
	"Yakirian",
	"Yan-C-Bin",
	"Yann-An-Oed",
	"Yaojing",
	"Yarnspinner",
	"Yathon",
	"Yavalnoi",
	"Ychen Bannog",
	"Yeenoghu",
	"Yeenoghu",
	"Yek",
	"Yellow Musk Creeper",
	"Yellow Musk Creeper",
	"Yellow Musk Zombie",
	"Yellow Musk Zombie",
	"Yellow Sign Attendant",
	"Yestabrod",
	"Yeth Hound",
	"Yeti Tyke",
	"Yeti",
	"Ygorl, Lord of Entropy",
	"Yochlol",
	"Yothan Commaner",
	"Yothan Designer",
	"Yothan Warrior",
	"Young Amethyst Dragon",
	"Young Black Dragon",
	"Young Black Zombie Dragon",
	"Young Blue Dragon Zombie",
	"Young Blue Dragon",
	"Young Boreal Dragon",
	"Young Brass Dragon",
	"Young Bronze Dragon",
	"Young Cave Dragon",
	"Young Copper Dragon",
	"Young Crystal Dragon",
	"Young Deep Dragon",
	"Young Dragon Turtle",
	"Young Emerald Dragon",
	"Young Faerie Dragon",
	"Young Flame Dragon",
	"Young Gold Dragon",
	"Young Green Dragon",
	"Young Imperial Dragon",
	"Young Kraken",
	"Young Kruthik",
	"Young Light Dragon",
	"Young Magma Landshark",
	"Young Mithral Dragon",
	"Young Moonstone Dragon",
	"Young Phoenix",
	"Young Red Dragon",
	"Young Red Shadow Dragon",
	"Young Remorhaz",
	"Young Sapphire Dragon",
	"Young Sea Dragon",
	"Young Sea Serpent",
	"Young Silver Dragon",
	"Young Spinosaurus",
	"Young Topaz Dragon",
	"Young Void Dragon",
	"Young Wasteland Dragon",
	"Young White Dragon",
	"Young Wind Dragon",
	"Yowler",
	"Yskarakta",
	"Yuan-Ti Abomination",
	"Yuan-Ti Anathema",
	"Yuan-Ti Anathema",
	"Yuan-Ti Broodguard",
	"Yuan-Ti Broodguard",
	"Yuan-Ti Malison",
	"Yuan-Ti Mind Whisperer",
	"Yuan-Ti Mind Whisperer",
	"Yuan-Ti Nightmare Speaker",
	"Yuan-Ti Nightmare Speaker",
	"Yuan-Ti Pit Master",
	"Yuan-Ti Pit Master",
	"Yuan-Ti Pureblood",
	"Yumerai",
	"Yusdrayl",
	"Zacama, Primal Calamity",
	"Zaiden",
	"Zakya Rakshasa",
	"Zalikum",
	"Zanskaran Viper",
	"Zarak",
	"Zaratan",
	"Zaratan",
	"Zaratan",
	"Zargash",
	"Zariel",
	"Zariel",
	"Zegana",
	"Zeitgeist",
	"Zergling",
	"Zetalpa, Primal Dawn",
	"Zikran",
	"Zikzokrishka",
	"Zimwi",
	"Zindar",
	"Ziphius",
	"Ziraj the Hunter",
	"Zmey",
	"Zombie Clot",
	"Zombie Plague Spreader",
	"Zombie Raven",
	"Zombie Troll",
	"Zombie",
	"Zoog Grove Keeper",
	"Zoog Trapper",
	"Zoog",
	"Zorbo",
	"Zoryas",
	"Zouyu",
	"Zuggtmoy",
	"Zuggtmoy",
	"Zyz, Scourge of the Skies",
};

static char *random_item_from_list(char **list, size_t len)
{
	return list[rand() % len];
}

char *MONSTER_GetRandomMonsterName(void)
{
	return random_item_from_list(DND_MONSTERS, ARRSIZE(DND_MONSTERS));
}

static char *ACTION_LIST[] = {
	"track", "locate", "farm", "kill"
};

char *MONSTER_GetMonsterQuestAction(void)
{
	return random_item_from_list(ACTION_LIST, ARRSIZE(ACTION_LIST));
}
