#ifndef RPG_H
#define RPG_H

// DESIGN - THINGS THAT CANNOT HAPPEN TO A PLAYER
//
// - Be overencumbered
// - Lose XP
// - Have their items/gold stolen
//
// DESIGN - THINGS THAT PLAYERS SHOULD BE ABLE TO DO
//
// - Dungeon Crawling (random chance with loot tables)
// - Raids (with Bosses, multiple people)
// - Get magic items
// - Sell/Buy/Trade items
// - Fish
// - Garden

#include "common.h"

typedef struct Inventory {
	i32 gold;
	i32 silver;
	i32 copper;
	i32 item_id[40];
} Inventory;

enum {
	ITEM_KIND_NONE,

	// MAIN HAND
	ITEM_KIND_MAINHAND_START,
	ITEM_KIND_SWORD,
	ITEM_KIND_MACE,
	ITEM_KIND_HAMMER,
	ITEM_KIND_AXE,
	ITEM_KIND_WAND,
	ITEM_KIND_HOLYSYMBOL,
	ITEM_KIND_PRAYERBOOK,
	ITEM_KIND_STAFF,
	ITEM_KIND_SPELLBOOK,
	ITEM_KIND_MAINHAND_END,

	ITEM_KIND_OFFHAND_START,
	ITEM_KIND_SHIELD,
	ITEM_KIND_BUCKLER,
	ITEM_KIND_DEFENDER,
	ITEM_KIND_DAGGER,
	ITEM_KIND_OFFHAND_END,

	ITEM_KIND_WEARABLE_START,
	ITEM_KIND_HELMIT,
	ITEM_KIND_SHIRT,
	ITEM_KIND_PANTS,
	ITEM_KIND_TROUSERS,
	ITEM_KIND_BREASTPLATE,
	ITEM_KIND_PLATELEGS,
	ITEM_KIND_ROBE,
	ITEM_KIND_SKIRT,
	ITEM_KIND_PAULDRON,
	ITEM_KIND_BOOTS,
	ITEM_KIND_SHOES,
	ITEM_KIND_SANDALS,
	ITEM_KIND_WEARABLE_END,

	ITEM_KIND_TOTAL
};

enum {
	ITEM_ATTR_NONE,

	ITEM_ATTR_ANCIENT,
	ITEM_ATTR_ARCANE,
	ITEM_ATTR_BLESSED,
	ITEM_ATTR_CURSED,
	ITEM_ATTR_DIVINE,
	ITEM_ATTR_ELDRITCH,
	ITEM_ATTR_ENCHANTED,
	ITEM_ATTR_EPIC,
	ITEM_ATTR_ETERNAL,
	ITEM_ATTR_EXOTIC,
	ITEM_ATTR_FLAMING,
	ITEM_ATTR_FROSTY,
	ITEM_ATTR_GHOSTLY,
	ITEM_ATTR_GLIMMERING,
	ITEM_ATTR_GLOWING,
	ITEM_ATTR_GOLDEN,
	ITEM_ATTR_GRIM,
	ITEM_ATTR_HAUNTED,
	ITEM_ATTR_HELLISH,
	ITEM_ATTR_HOLY,
	ITEM_ATTR_ILLUMINATED,
	ITEM_ATTR_IMMORTAL,
	ITEM_ATTR_IMPERIAL,
	ITEM_ATTR_INFUSED,
	ITEM_ATTR_JAGGED,
	ITEM_ATTR_LUMINOUS,
	ITEM_ATTR_LURID,
	ITEM_ATTR_MAGICAL,
	ITEM_ATTR_MYSTICAL,
	ITEM_ATTR_MYTHIC,
	ITEM_ATTR_OBSIDIAN,
	ITEM_ATTR_OCCULT,
	ITEM_ATTR_OTHERWORLDLY,
	ITEM_ATTR_PHANTASMAL,
	ITEM_ATTR_PRIMAL,
	ITEM_ATTR_PROPHETIC,
	ITEM_ATTR_RADIANT,
	ITEM_ATTR_RARE,
	ITEM_ATTR_RUNED,
	ITEM_ATTR_SACRED,
	ITEM_ATTR_SAVAGE,
	ITEM_ATTR_SHADOWY,
	ITEM_ATTR_SHIMMERING,
	ITEM_ATTR_SILVERED,
	ITEM_ATTR_SPECTRAL,
	ITEM_ATTR_SPELLBOUND,
	ITEM_ATTR_SPIRITUAL,
	ITEM_ATTR_STELLAR,
	ITEM_ATTR_STORMY,
	ITEM_ATTR_TERRIFYING,
	ITEM_ATTR_TITANIC,
	ITEM_ATTR_TWILIGHT,
	ITEM_ATTR_ULTIMATE,
	ITEM_ATTR_UNDYING,
	ITEM_ATTR_UNHOLY,
	ITEM_ATTR_VENGEFUL,
	ITEM_ATTR_VENERABLE,
	ITEM_ATTR_WARPED,
	ITEM_ATTR_WICKED,
	ITEM_ATTR_WONDROUS,
	ITEM_ATTR_ABYSSAL,
	ITEM_ATTR_ALCHEMICAL,
	ITEM_ATTR_BATTLEWORN,
	ITEM_ATTR_BLOODY,
	ITEM_ATTR_BRILLIANT,
	ITEM_ATTR_CALMING,
	ITEM_ATTR_CELESTIAL,
	ITEM_ATTR_CHARGED,
	ITEM_ATTR_CLOAKED,
	ITEM_ATTR_DARKENED,
	ITEM_ATTR_DIMENSIONAL,
	ITEM_ATTR_DREADFUL,
	ITEM_ATTR_EMBERED,
	ITEM_ATTR_FIENDISH,
	ITEM_ATTR_GLACIAL,
	ITEM_ATTR_HARMONIOUS,
	ITEM_ATTR_HEROIC,
	ITEM_ATTR_HONORABLE,
	ITEM_ATTR_INSCRIBED,
	ITEM_ATTR_LEGENDARY,
	ITEM_ATTR_MAGNETIC,
	ITEM_ATTR_MALEFIC,
	ITEM_ATTR_MARTIAL,
	ITEM_ATTR_NIGHTMARISH,
	ITEM_ATTR_OMINOUS,
	ITEM_ATTR_PIERCING,
	ITEM_ATTR_RELIC,
	ITEM_ATTR_SORCEROUS,
	ITEM_ATTR_THUNDEROUS,
	ITEM_ATTR_TRANSCENDENT,
	ITEM_ATTR_VIGILANT,
	ITEM_ATTR_VIVID,
	ITEM_ATTR_WARLOCK,
	ITEM_ATTR_WINDWORN,
	ITEM_ATTR_WRATHFUL,
	ITEM_ATTR_ZEALOUS,

	ITEM_ATTR_TOTAL
};

typedef struct Item {
	i32 kind;
	i32 attribute;
	char name[16];
} Item;

typedef struct Player {
	char nickname[64];
	i64 gp;
	i64 xp;
	Item items[3];
	i32 lock;
} Player;

void rpg_init(void);
void rpg_free(void);

Player *RPG_FindByNickname(char *nickname);
Player *RPG_AddPlayer(char *nickname);

void RPG_AddGP(Player *player, i64 gp);
void RPG_AddXP(Player *player, i64 gp);

// RPG_LockWithNickname: returns a pointer to the player, locking it in the process
Player *RPG_LockWithNickname(char *nickname);

// RPG_UnlockWithNickname: returns a pointer to the player, unlocking it in the process
Player *RPG_UnlockWithNickname(char *nickname);

i32 RPG_GetLevel(Player *player);

#endif // RPG_H
